In [67]:
import pandas as pd

df = pd.read_csv("test_data.csv")

In [68]:
df.head()

,reference_text,student_answer,expected_level
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,Partially Relevant
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,NaN,Not Related
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good

In [69]:
df.shape

(30, 3)

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reference_text  30 non-null     str
 1   student_answer  26 non-null     str
 2   expected_level  30 non-null     str
dtypes: str(3)
memory usage: 852.0 bytes

In [71]:
df.columns

Index(['reference_text', 'student_answer', 'expected_level'], dtype='str')

In [72]:
df.isnull()

    reference_text  student_answer  expected_level
0            False           False           False
1            False           False           False
2            False           False           False
3            False            True           False
4            False           False           False
5            False           False           False
6            False           False           False
7            False           False           False
8            False           False           False
9            False           False           False
10           False           False           False
11           False            True           False
12           False           False           False
13           False           False           False
14           False           False           False
15           False           False           False
16           False           False           False
17           False           False           False
18           False           False           False
19           False            True           False
20           False           False           False
21           False           False           False
22           False           False           False
23           False           False           False
24           False           False           False
25           False           False           False
26           False           False           False
27           False            True           False
28           False           False           False
29           False           False           False

In [73]:
df.isnull().sum()

reference_text    0
student_answer    4
expected_level    0
dtype: int64

In [74]:
df[df['student_answer'].isnull()]

,reference_text,student_answer,expected_level
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,NaN,Not Related
11,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,NaN,Not Related
19,DNA mang thông tin di truyền của sinh vật,NaN,Not Related
27,Kim loại dẫn điện tốt vì có electron tự do,NaN,Not Related

In [75]:
df_dropped = df.dropna(subset=['student_answer'])
df_dropped.shape

(26, 3)

In [76]:
df_filled = df.fillna({'student_answer': ''})
df_filled.isnull().sum()

reference_text    0
student_answer    0
expected_level    0
dtype: int64

In [77]:
print("Số dòng gốc:", df.shape[0])
print("Số dòng sau khi dropna:", df_dropped.shape[0])
print("Số dòng sau khi fillna:", df_filled.shape[0])

Số dòng gốc: 30
Số dòng sau khi dropna: 26
Số dòng sau khi fillna: 30

In [78]:
very_good_only = df[df['expected_level'] == 'Very Good']
very_good_only

,reference_text,student_answer,expected_level
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất di chuyển vòng quanh Mặt Trời,Very Good
12,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Vật có khối lượng thì hút nhau,Very Good
16,DNA mang thông tin di truyền của sinh vật,DNA chứa mã di truyền quy định đặc điểm sinh vật,Very Good
20,Áp suất khí quyển giảm dần khi lên cao,Càng lên cao áp suất không khí càng thấp,Very Good
24,Kim loại dẫn điện tốt vì có electron tự do,Electron tự do trong kim loại giúp dẫn điện,Very Good
28,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim bơm máu đi nuôi cơ thể,Very Good

In [79]:
# Very Good VÀ có student_answer không rỗng
result = df[(df['expected_level'] == 'Very Good') & (df['student_answer'].notnull())]
result

,reference_text,student_answer,expected_level
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất di chuyển vòng quanh Mặt Trời,Very Good
12,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Vật có khối lượng thì hút nhau,Very Good
16,DNA mang thông tin di truyền của sinh vật,DNA chứa mã di truyền quy định đặc điểm sinh vật,Very Good
20,Áp suất khí quyển giảm dần khi lên cao,Càng lên cao áp suất không khí càng thấp,Very Good
24,Kim loại dẫn điện tốt vì có electron tự do,Electron tự do trong kim loại giúp dẫn điện,Very Good
28,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim bơm máu đi nuôi cơ thể,Very Good

In [80]:
df['expected_level'].value_counts()

expected_level
Not Related           15
Very Good              8
Partially Relevant     7
Name: count, dtype: int64

In [81]:
df[['reference_text', 'student_answer']]

,reference_text,student_answer
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,NaN
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...
5,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây cần nước để sống và phát triển
6,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Con mèo là động vật có vú
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây không quang hợp vào ban đêm
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất di chuyển vòng quanh Mặt Trời
9,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Mặt Trời quay quanh Trái Đất
10,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất có hình tròn
11,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,NaN
12,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Vật có khối lượng thì hút nhau
13,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Trái Đất hút mọi vật xuống dưới
14,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Nam châm hút sắt
15,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Không có lực nào giữa hai vật có khối lượng
16,DNA mang thông tin di truyền của sinh vật,DNA chứa mã di truyền quy định đặc điểm sinh vật
17,DNA mang thông tin di truyền của sinh vật,DNA là một phần của tế bào
18,DNA mang thông tin di truyền của sinh vật,Protein cấu tạo nên cơ thể
19,DNA mang thông tin di truyền của sinh vật,NaN
20,Áp suất khí quyển giảm dần khi lên cao,Càng lên cao áp suất không khí càng thấp
21,Áp suất khí quyển giảm dần khi lên cao,Trên núi cao không khí loãng hơn
22,Áp suất khí quyển giảm dần khi lên cao,Áp suất khí quyển tăng khi lên cao
23,Áp suất khí quyển giảm dần khi lên cao,Nhiệt độ giảm khi lên cao
24,Kim loại dẫn điện tốt vì có electron tự do,Electron tự do trong kim loại giúp dẫn điện
25,Kim loại dẫn điện tốt vì có electron tự do,Kim loại có thể dẫn điện
26,Kim loại dẫn điện tốt vì có electron tự do,Gỗ không dẫn điện
27,Kim loại dẫn điện tốt vì có electron tự do,NaN
28,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim bơm máu đi nuôi cơ thể
29,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim không tham gia vào việc vận chuyển máu

In [82]:
df[df['expected_level'] == 'Partially Relevant'][['reference_text', 'student_answer']]

,reference_text,student_answer
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu
5,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây cần nước để sống và phát triển
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây không quang hợp vào ban đêm
13,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Trái Đất hút mọi vật xuống dưới
17,DNA mang thông tin di truyền của sinh vật,DNA là một phần của tế bào
21,Áp suất khí quyển giảm dần khi lên cao,Trên núi cao không khí loãng hơn
25,Kim loại dẫn điện tốt vì có electron tự do,Kim loại có thể dẫn điện

In [83]:
for index, row in df.iterrows():
    print(index, "-", row['reference_text'][:30], "->", row['student_answer'])

0 - Nước sôi ở 100 độ C tại áp suấ -> Nước sôi ở 100 độ C khi áp suất bình thường
1 - Nước sôi ở 100 độ C tại áp suấ -> Nước sôi khi đun nóng đủ lâu
2 - Nước sôi ở 100 độ C tại áp suấ -> Nước không sôi ở 100 độ C
3 - Nước sôi ở 100 độ C tại áp suấ -> nan
4 - Quang hợp là quá trình cây xan -> Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và nước
5 - Quang hợp là quá trình cây xan -> Cây cần nước để sống và phát triển
6 - Quang hợp là quá trình cây xan -> Con mèo là động vật có vú
7 - Quang hợp là quá trình cây xan -> Cây không quang hợp vào ban đêm
8 - Trái Đất quay quanh Mặt Trời t -> Trái Đất di chuyển vòng quanh Mặt Trời
9 - Trái Đất quay quanh Mặt Trời t -> Mặt Trời quay quanh Trái Đất
10 - Trái Đất quay quanh Mặt Trời t -> Trái Đất có hình tròn
11 - Trái Đất quay quanh Mặt Trời t -> nan
12 - Lực hấp dẫn là lực hút giữa ha -> Vật có khối lượng thì hút nhau
13 - Lực hấp dẫn là lực hút giữa ha -> Trái Đất hút mọi vật xuống dưới
14 - Lực hấp dẫn là lực hút giữa ha -> Nam châm hút sắt
15 - Lực hấp dẫn là lực hút giữa ha -> Không có lực nào giữa hai vật có khối lượng
16 - DNA mang thông tin di truyền c -> DNA chứa mã di truyền quy định đặc điểm sinh vật
17 - DNA mang thông tin di truyền c -> DNA là một phần của tế bào
18 - DNA mang thông tin di truyền c -> Protein cấu tạo nên cơ thể
19 - DNA mang thông tin di truyền c -> nan
20 - Áp suất khí quyển giảm dần khi -> Càng lên cao áp suất không khí càng thấp
21 - Áp suất khí quyển giảm dần khi -> Trên núi cao không khí loãng hơn
22 - Áp suất khí quyển giảm dần khi -> Áp suất khí quyển tăng khi lên cao
23 - Áp suất khí quyển giảm dần khi -> Nhiệt độ giảm khi lên cao
24 - Kim loại dẫn điện tốt vì có el -> Electron tự do trong kim loại giúp dẫn điện
25 - Kim loại dẫn điện tốt vì có el -> Kim loại có thể dẫn điện
26 - Kim loại dẫn điện tốt vì có el -> Gỗ không dẫn điện
27 - Kim loại dẫn điện tốt vì có el -> nan
28 - Hệ tuần hoàn vận chuyển máu đi -> Tim bơm máu đi nuôi cơ thể
29 - Hệ tuần hoàn vận chuyển máu đi -> Tim không tham gia vào việc vận chuyển máu

In [84]:
for index, row in df.iterrows():
    ref = row['reference_text']
    student = row['student_answer']
    expected = row['expected_level']
    
    # Giả lập: nếu student_answer trống -> luôn là Not Related
    if pd.isnull(student) or student.strip() == '':
        predicted = 'Not Related'
    else:
        predicted = 'Chưa tính được (chưa có model)'
    
    # So sánh dự đoán giả với nhãn thật
    match = "✓" if predicted == expected else "✗"
    print(f"[{index}] {match} Expected: {expected} | Predicted: {predicted}")

[0] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[1] ✗ Expected: Partially Relevant | Predicted: Chưa tính được (chưa có model)
[2] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[3] ✓ Expected: Not Related | Predicted: Not Related
[4] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[5] ✗ Expected: Partially Relevant | Predicted: Chưa tính được (chưa có model)
[6] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[7] ✗ Expected: Partially Relevant | Predicted: Chưa tính được (chưa có model)
[8] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[9] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[10] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[11] ✓ Expected: Not Related | Predicted: Not Related
[12] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[13] ✗ Expected: Partially Relevant | Predicted: Chưa tính được (chưa có model)
[14] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[15] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[16] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[17] ✗ Expected: Partially Relevant | Predicted: Chưa tính được (chưa có model)
[18] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[19] ✓ Expected: Not Related | Predicted: Not Related
[20] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[21] ✗ Expected: Partially Relevant | Predicted: Chưa tính được (chưa có model)
[22] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[23] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[24] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[25] ✗ Expected: Partially Relevant | Predicted: Chưa tính được (chưa có model)
[26] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[27] ✓ Expected: Not Related | Predicted: Not Related
[28] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[29] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)

In [85]:
# Cách này CHẬM hơn với dữ liệu lớn (không cần đổi gì bây giờ, chỉ để biết)
for index, row in df.iterrows():
    pass

# Cách nhanh hơn cho việc áp dụng 1 hàm lên toàn bộ cột (sẽ dùng ở Ngày 9, 13)
# df['result'] = df['student_answer'].apply(some_function)

In [86]:
df_filled = df.fillna({'student_answer': ''})

In [87]:
df_filled.to_csv("test_data_cleaned.csv", index=False)

In [88]:
check = pd.read_csv("test_data_cleaned.csv")
check.info()
check.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reference_text  30 non-null     str
 1   student_answer  26 non-null     str
 2   expected_level  30 non-null     str
dtypes: str(3)
memory usage: 852.0 bytes

reference_text    0
student_answer    4
expected_level    0
dtype: int64

In [89]:
def to_lowercase(text):
    return text.lower()

In [90]:
print(to_lowercase("Nước SÔI ở 100 Độ C"))
print(to_lowercase("KHÔNG có gì cả"))
print(to_lowercase("Trái Đất Quay Quanh Mặt Trời"))

nước sôi ở 100 độ c
không có gì cả
trái đất quay quanh mặt trời

In [91]:
def to_lowercase(text):
    if pd.isnull(text):
        return ""
    return str(text).lower()

In [92]:
def strip_whitespace(text):
    return text.strip()

In [93]:
import re

def normalize_spaces(text):
    return re.sub(r'\s+', ' ', text)

In [94]:
print(normalize_spaces("nước    sôi ở   100 độ"))
# → "nước sôi ở 100 độ"

nước sôi ở 100 độ

In [95]:
def clean_whitespace(text):
    if pd.isnull(text):
        return ""
    text = str(text).strip()          # xóa đầu/cuối trước
    text = re.sub(r'\s+', ' ', text)  # chuẩn hóa khoảng trắng giữa
    return text

In [96]:
print(clean_whitespace("   nước   sôi ở  100 độ C   "))
# → "nước sôi ở 100 độ C"

nước sôi ở 100 độ C

Bước 3.2: Viết hàm xóa dấu câu cơ bản
Giải thích:
string.punctuation — 1 chuỗi có sẵn trong thư viện string, liệt kê hết các ký tự dấu câu tiếng Anh chuẩn (bao gồm cả %, - — nên nếu dùng nguyên bản này sẽ xóa luôn cả 2 ký tự bạn có thể muốn giữ theo bảng ở Bước 3.1).
str.maketrans('', '', string.punctuation) — tạo ra 1 "bảng chuyển đổi" (translation table): 2 tham số đầu rỗng nghĩa là không thay ký tự nào bằng ký tự khác, tham số thứ 3 là danh sách ký tự cần xóa hẳn.
.translate(translator) — áp bảng chuyển đổi đó lên chuỗi.

In [97]:
import string

def remove_punctuation(text):
    # string.punctuation chứa: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

In [98]:
import string

def remove_punctuation(text):
    if pd.isnull(text):
        return ""
    # Loại bỏ dấu câu nhưng GIỮ LẠI ký tự %
    punctuation_to_remove = string.punctuation.replace('%', '')
    translator = str.maketrans('', '', punctuation_to_remove)
    return str(text).translate(translator)

In [99]:
test_cases = [
    "Nước sôi ở 100 độ C, đúng không?",
    "Tỷ lệ tăng 20% - rất đáng kể!",
    "Câu hỏi: Trái Đất có hình gì???",
]

for t in test_cases:
    print(f"Gốc:  {t}")
    print(f"Sạch: {remove_punctuation(t)}")
    print()

Gốc:  Nước sôi ở 100 độ C, đúng không?
Sạch: Nước sôi ở 100 độ C đúng không

Gốc:  Tỷ lệ tăng 20% - rất đáng kể!
Sạch: Tỷ lệ tăng 20%  rất đáng kể

Gốc:  Câu hỏi: Trái Đất có hình gì???
Sạch: Câu hỏi Trái Đất có hình gì

In [100]:
def clean_text(text):
    if pd.isnull(text):
        return ""
    
    text = str(text)
    text = to_lowercase(text)
    text = remove_punctuation(text)
    text = clean_whitespace(text)
    
    return text

In [101]:
test_cases = [
    "   Nước SÔI ở 100 Độ C,   đúng không???   ",
    "TỶ  Lệ   tăng 20%!!! - Rất Đáng   Kể",
    "",
    None,
]

for t in test_cases:
    print(f"Gốc:  {repr(t)}")
    print(f"Sạch: {repr(clean_text(t))}")
    print()

Gốc:  '   Nước SÔI ở 100 Độ C,   đúng không???   '
Sạch: 'nước sôi ở 100 độ c đúng không'

Gốc:  'TỶ  Lệ   tăng 20%!!! - Rất Đáng   Kể'
Sạch: 'tỷ lệ tăng 20% rất đáng kể'

Gốc:  ''
Sạch: ''

Gốc:  None
Sạch: ''

In [102]:
df = pd.read_csv("test_data.csv")
df.shape

(30, 3)

In [103]:
df['reference_text_clean'] = df['reference_text'].apply(clean_text)
df['student_answer_clean'] = df['student_answer'].apply(clean_text)

In [104]:
df.shape       # phải là (30, 5) — có thêm 2 cột mới
df.columns     # xác nhận tên 2 cột mới đã đúng

Index(['reference_text', 'student_answer', 'expected_level',
       'reference_text_clean', 'student_answer_clean'],
      dtype='str')

In [105]:
df[['reference_text', 'reference_text_clean']].head(10)

,reference_text,reference_text_clean
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...
5,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...
6,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,trái đất quay quanh mặt trời theo quỹ đạo hình...
9,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,trái đất quay quanh mặt trời theo quỹ đạo hình...

In [106]:
df[['student_answer', 'student_answer_clean']].head(10)

,student_answer,student_answer_clean
0,Nước sôi ở 100 độ C khi áp suất bình thường,nước sôi ở 100 độ c khi áp suất bình thường
1,Nước sôi khi đun nóng đủ lâu,nước sôi khi đun nóng đủ lâu
2,Nước không sôi ở 100 độ C,nước không sôi ở 100 độ c
3,NaN,
4,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,cây dùng ánh sáng để tạo ra thức ăn từ co2 và ...
5,Cây cần nước để sống và phát triển,cây cần nước để sống và phát triển
6,Con mèo là động vật có vú,con mèo là động vật có vú
7,Cây không quang hợp vào ban đêm,cây không quang hợp vào ban đêm
8,Trái Đất di chuyển vòng quanh Mặt Trời,trái đất di chuyển vòng quanh mặt trời
9,Mặt Trời quay quanh Trái Đất,mặt trời quay quanh trái đất

In [107]:
df[df['student_answer'].isnull()][['student_answer', 'student_answer_clean']]

   student_answer student_answer_clean
3             NaN
11            NaN
19            NaN
27            NaN

In [108]:
df['len_before'] = df['reference_text'].fillna('').apply(len)
df['len_after'] = df['reference_text_clean'].apply(len)
df[['reference_text', 'reference_text_clean', 'len_before', 'len_after']].head(10)

,reference_text,reference_text_clean,len_before,len_after
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,52,52
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,52,52
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,52,52
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,52,52
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...,81,81
5,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...,81,81
6,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...,81,81
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...,81,81
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,trái đất quay quanh mặt trời theo quỹ đạo hình...,51,51
9,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,trái đất quay quanh mặt trời theo quỹ đạo hình...,51,51

In [109]:
df_to_save = df.drop(columns=['len_before', 'len_after'])

In [110]:
df_to_save.to_csv("test_data_step3.csv", index=False)

In [111]:
check = pd.read_csv("test_data_step3.csv")
check.info()
check.head()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        26 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  26 non-null     str
dtypes: str(5)
memory usage: 1.3 KB

,reference_text,student_answer,expected_level,reference_text_clean,student_answer_clean
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c khi áp suất bình thường
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,Partially Relevant,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước sôi khi đun nóng đủ lâu
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước không sôi ở 100 độ c
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,NaN,Not Related,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,NaN
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good,quang hợp là quá trình cây xanh chuyển hóa co2...,cây dùng ánh sáng để tạo ra thức ăn từ co2 và ...

In [112]:
import inspect
print(inspect.getsource(clean_text))

def clean_text(text):
    if pd.isnull(text):
        return ""

    text = str(text)
    text = to_lowercase(text)
    text = remove_punctuation(text)
    text = clean_whitespace(text)

    return text

In [113]:
df['reference_text_clean'] = df['reference_text'].apply(clean_text)
df['student_answer_clean'] = df['student_answer'].apply(clean_text)

In [114]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        26 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  30 non-null     str
 5   len_before            30 non-null     int64
 6   len_after             30 non-null     int64
dtypes: int64(2), str(5)
memory usage: 1.8 KB

In [115]:
df.loc[3, ['student_answer', 'student_answer_clean']]

student_answer          NaN
student_answer_clean
Name: 3, dtype: str

In [116]:
print(repr(df.loc[3, 'student_answer_clean']))

''

In [117]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        26 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  30 non-null     str
 5   len_before            30 non-null     int64
 6   len_after             30 non-null     int64
dtypes: int64(2), str(5)
memory usage: 1.8 KB

In [118]:
df.to_csv("test_data_step3.csv", index=False)

In [119]:
check = pd.read_csv("test_data_step3.csv")
check.info()
check.head()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        26 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  26 non-null     str
 5   len_before            30 non-null     int64
 6   len_after             30 non-null     int64
dtypes: int64(2), str(5)
memory usage: 1.8 KB

,reference_text,student_answer,expected_level,reference_text_clean,student_answer_clean,len_before,len_after
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c khi áp suất bình thường,52,52
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,Partially Relevant,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước sôi khi đun nóng đủ lâu,52,52
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước không sôi ở 100 độ c,52,52
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,NaN,Not Related,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,NaN,52,52
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good,quang hợp là quá trình cây xanh chuyển hóa co2...,cây dùng ánh sáng để tạo ra thức ăn từ co2 và ...,81,81

In [120]:
df_to_save = df.drop(columns=['len_before', 'len_after'])
df_to_save.to_csv("test_data_step3.csv", index=False)

In [121]:
check = pd.read_csv("test_data_step3.csv")
check.info()
check.head()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        26 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  26 non-null     str
dtypes: str(5)
memory usage: 1.3 KB

,reference_text,student_answer,expected_level,reference_text_clean,student_answer_clean
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c khi áp suất bình thường
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,Partially Relevant,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước sôi khi đun nóng đủ lâu
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước không sôi ở 100 độ c
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,NaN,Not Related,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,NaN
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good,quang hợp là quá trình cây xanh chuyển hóa co2...,cây dùng ánh sáng để tạo ra thức ăn từ co2 và ...

In [122]:
check = pd.read_csv("test_data_step3.csv", keep_default_na=False, na_values=[])
check.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        30 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  30 non-null     str
dtypes: str(5)
memory usage: 1.3 KB

In [123]:
check.info()
print(repr(check.loc[3, 'student_answer_clean']))

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        30 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  30 non-null     str
dtypes: str(5)
memory usage: 1.3 KB
''

In [124]:
import sklearn
print(sklearn.__version__)

1.9.0

In [125]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

In [126]:
sentences = [
    "nước sôi ở 100 độ c",
    "nước sôi khi đun nóng đủ lâu"
]

vectors = vectorizer.fit_transform(sentences)
print(vectors.shape)

(2, 9)

In [127]:
print(vectorizer.get_feature_names_out())

['100' 'khi' 'lâu' 'nóng' 'nước' 'sôi' 'đun' 'độ' 'đủ']

In [128]:
print(vectors.toarray())

[[0.57615236 0.         0.         0.         0.40993715 0.40993715
  0.         0.57615236 0.        ]
 [0.         0.4078241  0.4078241  0.4078241  0.29017021 0.29017021
  0.4078241  0.         0.4078241 ]]

In [129]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

In [130]:
# Gộp TOÀN BỘ câu (cả reference và student answer) để fit 1 lần duy nhất
all_texts = [
    "nước sôi ở 100 độ c",
    "nước sôi khi đun nóng đủ lâu",
    "trái đất quay quanh mặt trời",
    "mặt trời quay quanh trái đất"
]

vectorizer3 = TfidfVectorizer()
vectorizer3.fit(all_texts)   # học từ vựng 1 LẦN từ TOÀN BỘ dữ liệu

# Sau đó, transform từng câu riêng lẻ khi cần so sánh
ref_vector = vectorizer3.transform(["nước sôi ở 100 độ c"])
student_vector = vectorizer3.transform(["nước sôi khi đun nóng đủ lâu"])

print(ref_vector.shape, student_vector.shape)

(1, 15) (1, 15)

In [131]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_score = cosine_similarity(ref_vector, student_vector)
print(similarity_score)

[[0.27627837]]

In [132]:
def compute_similarity(text1, text2, vectorizer):
    vec1 = vectorizer.transform([text1])
    vec2 = vectorizer.transform([text2])
    score = cosine_similarity(vec1, vec2)
    return score[0][0]

In [133]:
test_corpus = [
    "nước sôi ở 100 độ c",
    "nước sôi khi đun nóng đủ lâu",
    "nước không sôi ở 100 độ c",
    "con mèo là động vật có vú",
    "h2o bắt đầu sôi tại 100 độ c"
]

test_vectorizer = TfidfVectorizer()
test_vectorizer.fit(test_corpus)

TfidfVectorizer()

In [134]:
score1 = compute_similarity(
    "nước sôi ở 100 độ c",
    "nước sôi ở 100 độ c",
    test_vectorizer
)
print("Giống hệt nhau:", score1)

Giống hệt nhau: 1.0

In [135]:
score2 = compute_similarity(
    "nước sôi ở 100 độ c",
    "con mèo là động vật có vú",
    test_vectorizer
)
print("Khác chủ đề hoàn toàn:", score2)

Khác chủ đề hoàn toàn: 0.0

In [136]:
score3 = compute_similarity(
    "nước sôi ở 100 độ c",
    "h2o bắt đầu sôi tại 100 độ c",
    test_vectorizer
)
print("Cùng nghĩa, khác từ vựng:", score3)

Cùng nghĩa, khác từ vựng: 0.41241057563632105

In [137]:
score4 = compute_similarity(
    "nước sôi ở 100 độ c",
    "nước không sôi ở 100 độ c",
    test_vectorizer
)
print("Câu phủ định:", score4)

Câu phủ định: 0.790237525025349

In [138]:
print(f"{'Test case':<35}{'Score':>10}")
print(f"{'Giống hệt nhau':<35}{score1:>10.3f}")
print(f"{'Khác chủ đề hoàn toàn':<35}{score2:>10.3f}")
print(f"{'Cùng nghĩa, khác từ vựng':<35}{score3:>10.3f}")
print(f"{'Câu phủ định':<35}{score4:>10.3f}")

Test case                               Score
Giống hệt nhau                          1.000
Khác chủ đề hoàn toàn                   0.000
Cùng nghĩa, khác từ vựng                0.412
Câu phủ định                            0.790

In [139]:
df = pd.read_csv("test_data_step3.csv", keep_default_na=False, na_values=[])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        30 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  30 non-null     str
dtypes: str(5)
memory usage: 1.3 KB

In [140]:
all_texts_real = pd.concat([
    df['reference_text_clean'],
    df['student_answer_clean']
]).tolist()

print(len(all_texts_real))   # phải ra 60 (30 dòng x 2 cột)

main_vectorizer = TfidfVectorizer()
main_vectorizer.fit(all_texts_real)

print(len(main_vectorizer.get_feature_names_out()))   # tổng số từ vựng thật của dataset

60
146

In [141]:
similarities = []

for index, row in df.iterrows():
    ref = row['reference_text_clean']
    student = row['student_answer_clean']
    score = compute_similarity(ref, student, main_vectorizer)
    similarities.append(score)

df['tfidf_similarity'] = similarities

In [142]:
df[['reference_text', 'student_answer', 'expected_level', 'tfidf_similarity']].head(10)

,reference_text,student_answer,expected_level,tfidf_similarity
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good,0.493744
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,Partially Relevant,0.151702
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related,0.522373
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,,Not Related,0.000000
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good,0.317314
5,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây cần nước để sống và phát triển,Partially Relevant,0.172715
6,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Con mèo là động vật có vú,Not Related,0.055544
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây không quang hợp vào ban đêm,Partially Relevant,0.238201
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất di chuyển vòng quanh Mặt Trời,Very Good,0.469244
9,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Mặt Trời quay quanh Trái Đất,Not Related,0.701062

In [143]:
df.groupby('expected_level')['tfidf_similarity'].mean()

expected_level
Not Related           0.278286
Partially Relevant    0.237227
Very Good             0.441636
Name: tfidf_similarity, dtype: float64

In [144]:
df.groupby('expected_level')['tfidf_similarity'].describe()

,count,mean,std,min,25%,50%,75%,max
expected_level,,,,,,,,
Not Related,15.0,0.278286,0.283137,0.000000,0.000000,0.240586,0.520500,0.719199
Partially Relevant,7.0,0.237227,0.154556,0.138650,0.161814,0.172715,0.223144,0.579305
Very Good,8.0,0.441636,0.107574,0.317314,0.377030,0.422044,0.475369,0.665627

In [145]:
suspicious = df[(df['expected_level'] == 'Very Good') & (df['tfidf_similarity'] < 0.5)]
suspicious[['reference_text', 'student_answer', 'tfidf_similarity']]

,reference_text,student_answer,tfidf_similarity
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,0.493744
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,0.317314
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất di chuyển vòng quanh Mặt Trời,0.469244
12,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Vật có khối lượng thì hút nhau,0.399001
16,DNA mang thông tin di truyền của sinh vật,DNA chứa mã di truyền quy định đặc điểm sinh vật,0.382525
20,Áp suất khí quyển giảm dần khi lên cao,Càng lên cao áp suất không khí càng thấp,0.360545
28,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim bơm máu đi nuôi cơ thể,0.445087

In [146]:
suspicious2 = df[(df['expected_level'] == 'Not Related') & (df['tfidf_similarity'] > 0.5)]
suspicious2[['reference_text', 'student_answer', 'tfidf_similarity']]

,reference_text,student_answer,tfidf_similarity
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,0.522373
9,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Mặt Trời quay quanh Trái Đất,0.701062
15,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Không có lực nào giữa hai vật có khối lượng,0.671694
22,Áp suất khí quyển giảm dần khi lên cao,Áp suất khí quyển tăng khi lên cao,0.719199
23,Áp suất khí quyển giảm dần khi lên cao,Nhiệt độ giảm khi lên cao,0.518627

In [147]:
df.to_csv("test_data_step4.csv", index=False)

In [148]:
check = pd.read_csv("test_data_step4.csv", keep_default_na=False, na_values=[])
check.info()
check[['expected_level', 'tfidf_similarity']].groupby('expected_level').mean()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        30 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  30 non-null     str
 5   tfidf_similarity      30 non-null     float64
dtypes: float64(1), str(5)
memory usage: 1.5 KB

                    tfidf_similarity
expected_level
Not Related                 0.278286
Partially Relevant          0.237227
Very Good                   0.441636

In [149]:
import numpy
print(numpy.__version__)

import torch
print(torch.__version__)

import sentence_transformers
print(sentence_transformers.__version__)

1.26.4
2.2.2
2.6.1

In [150]:
import numpy
print(numpy.__version__)

import scipy
print(scipy.__version__)

import torch
print(torch.__version__)

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

test_embedding = model.encode("nước sôi ở 100 độ c")
print(test_embedding.shape)

1.26.4
1.12.0
2.2.2
(384,)

In [151]:
import pandas as pd
df = pd.read_csv("test_data_step4.csv", keep_default_na=False, na_values=[])
print(df.shape)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
print("sklearn OK")

(30, 6)
sklearn OK

In [152]:
def encode_text(text):
    return model.encode(text)
vec1 = encode_text("trái đất quay quanh mặt trời theo quỹ đạo hình elip")
vec2 = encode_text("mặt trời quay quanh trái đất")

print(vec1.shape, vec2.shape)

(384,) (384,)

In [153]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def compute_semantic_similarity(text1, text2):
    vec1 = encode_text(text1).reshape(1, -1)
    vec2 = encode_text(text2).reshape(1, -1)
    score = cosine_similarity(vec1, vec2)
    return score[0][0]

In [154]:
score = compute_semantic_similarity(
    "nước sôi ở 100 độ c",
    "h2o bắt đầu sôi tại 100 độ c"
)
print(score)

0.81724036

In [155]:
negation_cases = [
    ("Nước sôi ở 100 độ C tại áp suất khí quyển tiêu chuẩn", "Nước không sôi ở 100 độ C", 0.522373),
    ("Trái Đất quay quanh Mặt Trời theo quỹ đạo hình elip", "Mặt Trời quay quanh Trái Đất", 0.701062),
    ("Lực hấp dẫn là lực hút giữa hai vật có khối lượng", "Không có lực nào giữa hai vật có khối lượng", 0.671694),
    ("Áp suất khí quyển giảm dần khi lên cao", "Áp suất khí quyển tăng khi lên cao", 0.719199),
    ("Áp suất khí quyển giảm dần khi lên cao", "Nhiệt độ giảm khi lên cao", 0.518627),
]

print(f"{'TF-IDF':>10}{'Semantic':>12}")
for ref, student, tfidf_score in negation_cases:
    sem_score = compute_semantic_similarity(ref, student)
    print(f"{tfidf_score:>10.3f}{sem_score:>12.3f}   {student[:40]}")

    TF-IDF    Semantic
     0.522       0.799   Nước không sôi ở 100 độ C
     0.701       0.886   Mặt Trời quay quanh Trái Đất
     0.672       0.682   Không có lực nào giữa hai vật có khối lư
     0.719       0.730   Áp suất khí quyển tăng khi lên cao
     0.519       0.774   Nhiệt độ giảm khi lên cao

In [156]:
paraphrase_cases = [
    ("Nước sôi ở 100 độ C tại áp suất khí quyển tiêu chuẩn", "Nước sôi ở 100 độ C khi áp suất bình thường", 0.493744),
    ("Quang hợp là quá trình cây xanh chuyển hóa CO2 và nước thành glucose nhờ ánh sáng", "Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và nước", 0.317314),
    ("Trái Đất quay quanh Mặt Trời theo quỹ đạo hình elip", "Trái Đất di chuyển vòng quanh Mặt Trời", 0.469244),
    ("Lực hấp dẫn là lực hút giữa hai vật có khối lượng", "Vật có khối lượng thì hút nhau", 0.399001),
    ("DNA mang thông tin di truyền của sinh vật", "DNA chứa mã di truyền quy định đặc điểm sinh vật", 0.382525),
    ("Áp suất khí quyển giảm dần khi lên cao", "Càng lên cao áp suất không khí càng thấp", 0.360545),
    ("Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ tim co bóp", "Tim bơm máu đi nuôi cơ thể", 0.445087),
]

print(f"{'TF-IDF':>10}{'Semantic':>12}")
for ref, student, tfidf_score in paraphrase_cases:
    sem_score = compute_semantic_similarity(ref, student)
    print(f"{tfidf_score:>10.3f}{sem_score:>12.3f}   {student[:40]}")

    TF-IDF    Semantic
     0.494       0.974   Nước sôi ở 100 độ C khi áp suất bình thư
     0.317       0.796   Cây dùng ánh sáng để tạo ra thức ăn từ C
     0.469       0.930   Trái Đất di chuyển vòng quanh Mặt Trời
     0.399       0.652   Vật có khối lượng thì hút nhau
     0.383       0.918   DNA chứa mã di truyền quy định đặc điểm
     0.361       0.690   Càng lên cao áp suất không khí càng thấp
     0.445       0.675   Tim bơm máu đi nuôi cơ thể

In [157]:
df = pd.read_csv("test_data_step4.csv", keep_default_na=False, na_values=[])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        30 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  30 non-null     str
 5   tfidf_similarity      30 non-null     float64
dtypes: float64(1), str(5)
memory usage: 1.5 KB

In [158]:
ref_embeddings = model.encode(df['reference_text_clean'].tolist())
student_embeddings = model.encode(df['student_answer_clean'].tolist())

print(ref_embeddings.shape, student_embeddings.shape)

(30, 384) (30, 384)

In [159]:
from sklearn.metrics.pairwise import cosine_similarity

semantic_scores = []
for i in range(len(df)):
    vec1 = ref_embeddings[i].reshape(1, -1)
    vec2 = student_embeddings[i].reshape(1, -1)
    score = cosine_similarity(vec1, vec2)[0][0]
    semantic_scores.append(score)

df['semantic_similarity'] = semantic_scores

In [160]:
df[['reference_text', 'student_answer', 'expected_level', 'tfidf_similarity', 'semantic_similarity']].head(10)

,reference_text,student_answer,expected_level,tfidf_similarity,semantic_similarity
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good,0.493744,0.973728
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,Partially Relevant,0.151702,0.714467
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related,0.522373,0.807460
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,,Not Related,0.000000,0.039252
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good,0.317314,0.792694
5,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây cần nước để sống và phát triển,Partially Relevant,0.172715,0.436551
6,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Con mèo là động vật có vú,Not Related,0.055544,0.105503
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây không quang hợp vào ban đêm,Partially Relevant,0.238201,0.426095
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất di chuyển vòng quanh Mặt Trời,Very Good,0.469244,0.912335
9,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Mặt Trời quay quanh Trái Đất,Not Related,0.701062,0.862312

In [161]:
comparison = df.groupby('expected_level')[['tfidf_similarity', 'semantic_similarity']].mean()
print(comparison)

                    tfidf_similarity  semantic_similarity
expected_level
Not Related                 0.278286             0.455907
Partially Relevant          0.237227             0.517955
Very Good                   0.441636             0.853330

In [162]:
df.groupby('expected_level')[['tfidf_similarity', 'semantic_similarity']].describe()

                   tfidf_similarity                                          \
                              count      mean       std       min       25%
expected_level
Not Related                    15.0  0.278286  0.283137  0.000000  0.000000
Partially Relevant              7.0  0.237227  0.154556  0.138650  0.161814
Very Good                       8.0  0.441636  0.107574  0.317314  0.377030

                                                 semantic_similarity  \
                         50%       75%       max               count
expected_level
Not Related         0.240586  0.520500  0.719199                15.0
Partially Relevant  0.172715  0.223144  0.579305                 7.0
Very Good           0.422044  0.475369  0.665627                 8.0

                                                                      \
                        mean       std       min       25%       50%
expected_level
Not Related         0.455907  0.319900  0.021498  0.130181  0.410382
Partially Relevant  0.517955  0.168481  0.285058  0.431323  0.466269
Very Good           0.853330  0.097911  0.666584  0.806245  0.871971


                         75%       max
expected_level
Not Related         0.731131  0.862312
Partially Relevant  0.625006  0.761699
Very Good           0.915900  0.973728

In [163]:
df['improvement'] = df['semantic_similarity'] - df['tfidf_similarity']
df[['reference_text', 'student_answer', 'expected_level', 'tfidf_similarity', 'semantic_similarity', 'improvement']].sort_values('improvement', ascending=False).head(10)

,reference_text,student_answer,expected_level,tfidf_similarity,semantic_similarity,improvement
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,Partially Relevant,0.151702,0.714467,0.562765
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good,0.493744,0.973728,0.479983
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good,0.317314,0.792694,0.475381
20,Áp suất khí quyển giảm dần khi lên cao,Càng lên cao áp suất không khí càng thấp,Very Good,0.360545,0.835203,0.474658
28,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim bơm máu đi nuôi cơ thể,Very Good,0.445087,0.908739,0.463651
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất di chuyển vòng quanh Mặt Trời,Very Good,0.469244,0.912335,0.443092
16,DNA mang thông tin di truyền của sinh vật,DNA chứa mã di truyền quy định đặc điểm sinh vật,Very Good,0.382525,0.810761,0.428236
18,DNA mang thông tin di truyền của sinh vật,Protein cấu tạo nên cơ thể,Not Related,0.000000,0.410382,0.410382
29,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim không tham gia vào việc vận chuyển máu,Not Related,0.296984,0.695855,0.398871
10,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất có hình tròn,Not Related,0.351791,0.737378,0.385588

In [164]:
still_wrong = df[(df['expected_level'] == 'Not Related') & (df['semantic_similarity'] > 0.6)]
still_wrong[['reference_text', 'student_answer', 'tfidf_similarity', 'semantic_similarity']]

,reference_text,student_answer,tfidf_similarity,semantic_similarity
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,0.522373,0.807460
9,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Mặt Trời quay quanh Trái Đất,0.701062,0.862312
10,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất có hình tròn,0.351791,0.737378
15,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Không có lực nào giữa hai vật có khối lượng,0.671694,0.686041
22,Áp suất khí quyển giảm dần khi lên cao,Áp suất khí quyển tăng khi lên cao,0.719199,0.808869
23,Áp suất khí quyển giảm dần khi lên cao,Nhiệt độ giảm khi lên cao,0.518627,0.724883
29,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim không tham gia vào việc vận chuyển máu,0.296984,0.695855

In [165]:
still_wrong[['tfidf_similarity', 'semantic_similarity']].mean()

tfidf_similarity       0.540247
semantic_similarity    0.760400
dtype: float64

In [166]:
df.to_csv("test_data_step5.csv", index=False)

check = pd.read_csv("test_data_step5.csv", keep_default_na=False, na_values=[])
check.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        30 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  30 non-null     str
 5   tfidf_similarity      30 non-null     float64
 6   semantic_similarity   30 non-null     float64
 7   improvement           30 non-null     float64
dtypes: float64(3), str(5)
memory usage: 2.0 KB

In [167]:
df = pd.read_csv("test_data_step5.csv", keep_default_na=False, na_values=[])

df.groupby('expected_level')['semantic_similarity'].describe()

,count,mean,std,min,25%,50%,75%,max
expected_level,,,,,,,,
Not Related,15.0,0.455907,0.319900,0.021498,0.130181,0.410382,0.731131,0.862312
Partially Relevant,7.0,0.517955,0.168481,0.285058,0.431323,0.466269,0.625006,0.761699
Very Good,8.0,0.853330,0.097911,0.666584,0.806245,0.871971,0.915900,0.973728

In [168]:
for level in ['Not Related', 'Partially Relevant', 'Very Good']:
    subset = df[df['expected_level'] == level]['semantic_similarity']
    print(f"{level}:")
    print(f"  min={subset.min():.3f}, 25%={subset.quantile(0.25):.3f}, median={subset.median():.3f}, 75%={subset.quantile(0.75):.3f}, max={subset.max():.3f}")
    print()

Not Related:
  min=0.021, 25%=0.130, median=0.410, 75%=0.731, max=0.862

Partially Relevant:
  min=0.285, 25%=0.431, median=0.466, 75%=0.625, max=0.762

Very Good:
  min=0.667, 25%=0.806, median=0.872, 75%=0.916, max=0.974

In [169]:
for level in ['Not Related', 'Partially Relevant', 'Very Good']:
    values = sorted(df[df['expected_level'] == level]['semantic_similarity'].tolist())
    print(f"{level}: {[round(v, 2) for v in values]}")

Not Related: [0.02, 0.04, 0.05, 0.11, 0.15, 0.35, 0.38, 0.41, 0.69, 0.7, 0.72, 0.74, 0.81, 0.81, 0.86]
Partially Relevant: [0.29, 0.43, 0.44, 0.47, 0.54, 0.71, 0.76]
Very Good: [0.67, 0.79, 0.81, 0.84, 0.91, 0.91, 0.93, 0.97]

In [170]:
THRESHOLD_VERY_GOOD = 0.70   # >= 0.70 → Very Good
THRESHOLD_PARTIAL = 0.45     # >= 0.45 và < 0.70 → Partially Relevant
                              # < 0.45 → Not Related

In [171]:
def classify_by_threshold(similarity_score, threshold_very_good=0.70, threshold_partial=0.45):
    if similarity_score >= threshold_very_good:
        return "Very Good"
    elif similarity_score >= threshold_partial:
        return "Partially Relevant"
    else:
        return "Not Related"

In [172]:
print(classify_by_threshold(0.85))   # kỳ vọng: Very Good
print(classify_by_threshold(0.55))   # kỳ vọng: Partially Relevant
print(classify_by_threshold(0.30))   # kỳ vọng: Not Related
print(classify_by_threshold(0.70))   # kỳ vọng: Very Good (đúng bằng ngưỡng, dùng >=)

Very Good
Partially Relevant
Not Related
Very Good

In [173]:
df['predicted_level'] = df['semantic_similarity'].apply(classify_by_threshold)
df[['reference_text', 'student_answer', 'expected_level', 'semantic_similarity', 'predicted_level']].head(10)

,reference_text,student_answer,expected_level,semantic_similarity,predicted_level
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good,0.973728,Very Good
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,Partially Relevant,0.714467,Very Good
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related,0.807460,Very Good
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,,Not Related,0.039252,Not Related
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good,0.792694,Very Good
5,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây cần nước để sống và phát triển,Partially Relevant,0.436551,Not Related
6,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Con mèo là động vật có vú,Not Related,0.105503,Not Related
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây không quang hợp vào ban đêm,Partially Relevant,0.426095,Not Related
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất di chuyển vòng quanh Mặt Trời,Very Good,0.912335,Very Good
9,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Mặt Trời quay quanh Trái Đất,Not Related,0.862312,Very Good

In [174]:
df['is_correct'] = df['expected_level'] == df['predicted_level']
accuracy = df['is_correct'].mean()
print(f"Accuracy: {accuracy:.2%}")

Accuracy: 56.67%

In [175]:
wrong_predictions = df[~df['is_correct']]
wrong_predictions[['reference_text', 'student_answer', 'expected_level', 'semantic_similarity', 'predicted_level']]

,reference_text,student_answer,expected_level,semantic_similarity,predicted_level
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,Partially Relevant,0.714467,Very Good
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related,0.807460,Very Good
5,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây cần nước để sống và phát triển,Partially Relevant,0.436551,Not Related
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây không quang hợp vào ban đêm,Partially Relevant,0.426095,Not Related
9,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Mặt Trời quay quanh Trái Đất,Not Related,0.862312,Very Good
10,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất có hình tròn,Not Related,0.737378,Very Good
12,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Vật có khối lượng thì hút nhau,Very Good,0.666584,Partially Relevant
13,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Trái Đất hút mọi vật xuống dưới,Partially Relevant,0.285058,Not Related
15,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Không có lực nào giữa hai vật có khối lượng,Not Related,0.686041,Partially Relevant
22,Áp suất khí quyển giảm dần khi lên cao,Áp suất khí quyển tăng khi lên cao,Not Related,0.808869,Very Good
23,Áp suất khí quyển giảm dần khi lên cao,Nhiệt độ giảm khi lên cao,Not Related,0.724883,Very Good
25,Kim loại dẫn điện tốt vì có electron tự do,Kim loại có thể dẫn điện,Partially Relevant,0.761699,Very Good
29,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim không tham gia vào việc vận chuyển máu,Not Related,0.695855,Partially Relevant

In [176]:
wrong_predictions[wrong_predictions['expected_level'] == 'Not Related']

,reference_text,student_answer,expected_level,reference_text_clean,student_answer_clean,tfidf_similarity,semantic_similarity,improvement,predicted_level,is_correct
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước không sôi ở 100 độ c,0.522373,0.807460,0.285087,Very Good,False
9,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Mặt Trời quay quanh Trái Đất,Not Related,trái đất quay quanh mặt trời theo quỹ đạo hình...,mặt trời quay quanh trái đất,0.701062,0.862312,0.161250,Very Good,False
10,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất có hình tròn,Not Related,trái đất quay quanh mặt trời theo quỹ đạo hình...,trái đất có hình tròn,0.351791,0.737378,0.385588,Very Good,False
15,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Không có lực nào giữa hai vật có khối lượng,Not Related,lực hấp dẫn là lực hút giữa hai vật có khối lượng,không có lực nào giữa hai vật có khối lượng,0.671694,0.686041,0.014347,Partially Relevant,False
22,Áp suất khí quyển giảm dần khi lên cao,Áp suất khí quyển tăng khi lên cao,Not Related,áp suất khí quyển giảm dần khi lên cao,áp suất khí quyển tăng khi lên cao,0.719199,0.808869,0.089671,Very Good,False
23,Áp suất khí quyển giảm dần khi lên cao,Nhiệt độ giảm khi lên cao,Not Related,áp suất khí quyển giảm dần khi lên cao,nhiệt độ giảm khi lên cao,0.518627,0.724883,0.206256,Very Good,False
29,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim không tham gia vào việc vận chuyển máu,Not Related,hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,tim không tham gia vào việc vận chuyển máu,0.296984,0.695855,0.398871,Partially Relevant,False

In [177]:
wrong_predictions = df[~df['is_correct']]
print(f"Tổng số dòng sai: {len(wrong_predictions)}")
print()
wrong_predictions[['reference_text', 'student_answer', 'expected_level', 'semantic_similarity', 'predicted_level']]

Tổng số dòng sai: 13

,reference_text,student_answer,expected_level,semantic_similarity,predicted_level
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,Partially Relevant,0.714467,Very Good
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related,0.807460,Very Good
5,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây cần nước để sống và phát triển,Partially Relevant,0.436551,Not Related
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây không quang hợp vào ban đêm,Partially Relevant,0.426095,Not Related
9,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Mặt Trời quay quanh Trái Đất,Not Related,0.862312,Very Good
10,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất có hình tròn,Not Related,0.737378,Very Good
12,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Vật có khối lượng thì hút nhau,Very Good,0.666584,Partially Relevant
13,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Trái Đất hút mọi vật xuống dưới,Partially Relevant,0.285058,Not Related
15,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Không có lực nào giữa hai vật có khối lượng,Not Related,0.686041,Partially Relevant
22,Áp suất khí quyển giảm dần khi lên cao,Áp suất khí quyển tăng khi lên cao,Not Related,0.808869,Very Good
23,Áp suất khí quyển giảm dần khi lên cao,Nhiệt độ giảm khi lên cao,Not Related,0.724883,Very Good
25,Kim loại dẫn điện tốt vì có electron tự do,Kim loại có thể dẫn điện,Partially Relevant,0.761699,Very Good
29,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim không tham gia vào việc vận chuyển máu,Not Related,0.695855,Partially Relevant

In [178]:
wrong_predictions['expected_level'].value_counts()

expected_level
Not Related           7
Partially Relevant    5
Very Good             1
Name: count, dtype: int64

In [179]:
pd.crosstab(wrong_predictions['expected_level'], wrong_predictions['predicted_level'])

predicted_level     Not Related  Partially Relevant  Very Good
expected_level
Not Related                   0                   2          5
Partially Relevant            3                   0          2
Very Good                     0                   1          0

In [180]:
partial_wrong = df[(df['expected_level'] == 'Partially Relevant') & (~df['is_correct'])]
partial_wrong[['reference_text', 'student_answer', 'semantic_similarity', 'predicted_level']]

,reference_text,student_answer,semantic_similarity,predicted_level
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,0.714467,Very Good
5,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây cần nước để sống và phát triển,0.436551,Not Related
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây không quang hợp vào ban đêm,0.426095,Not Related
13,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Trái Đất hút mọi vật xuống dưới,0.285058,Not Related
25,Kim loại dẫn điện tốt vì có electron tự do,Kim loại có thể dẫn điện,0.761699,Very Good

In [181]:
vg_wrong = df[(df['expected_level'] == 'Very Good') & (~df['is_correct'])]
vg_wrong[['reference_text', 'student_answer', 'semantic_similarity', 'predicted_level']]

,reference_text,student_answer,semantic_similarity,predicted_level
12,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Vật có khối lượng thì hút nhau,0.666584,Partially Relevant

In [182]:
def classify_by_threshold_v2(similarity_score, threshold_very_good=0.72, threshold_partial=0.40):
    if similarity_score >= threshold_very_good:
        return "Very Good"
    elif similarity_score >= threshold_partial:
        return "Partially Relevant"
    else:
        return "Not Related"

df['predicted_level_v2'] = df['semantic_similarity'].apply(classify_by_threshold_v2)
df['is_correct_v2'] = df['expected_level'] == df['predicted_level_v2']
accuracy_v2 = df['is_correct_v2'].mean()
print(f"Accuracy v1 (0.70/0.45): {df['is_correct'].mean():.2%}")
print(f"Accuracy v2 (0.72/0.40): {accuracy_v2:.2%}")

Accuracy v1 (0.70/0.45): 56.67%
Accuracy v2 (0.72/0.40): 63.33%

In [183]:
THRESHOLD_VERY_GOOD = 0.72
THRESHOLD_PARTIAL = 0.40

def classify_by_threshold(similarity_score, threshold_very_good=THRESHOLD_VERY_GOOD, threshold_partial=THRESHOLD_PARTIAL):
    if similarity_score >= threshold_very_good:
        return "Very Good"
    elif similarity_score >= threshold_partial:
        return "Partially Relevant"
    else:
        return "Not Related"

In [184]:
df['predicted_level'] = df['semantic_similarity'].apply(classify_by_threshold)
df['is_correct'] = df['expected_level'] == df['predicted_level']
print(f"Accuracy (chỉ dùng ngưỡng): {df['is_correct'].mean():.2%}")

Accuracy (chỉ dùng ngưỡng): 63.33%

In [185]:
def has_asymmetric_negation(text1, text2):
    negation_words = ["không", "chẳng", "chả"]
    
    text1_has_negation = any(word in text1.split() for word in negation_words)
    text2_has_negation = any(word in text2.split() for word in negation_words)
    
    return text1_has_negation != text2_has_negation

In [186]:
print(has_asymmetric_negation(
    "nước sôi ở 100 độ c",
    "nước không sôi ở 100 độ c"
))  # kỳ vọng: True

print(has_asymmetric_negation(
    "lực hấp dẫn là lực hút giữa hai vật có khối lượng",
    "không có lực nào giữa hai vật có khối lượng"
))  # kỳ vọng: True

print(has_asymmetric_negation(
    "hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ tim co bóp",
    "tim không tham gia vào việc vận chuyển máu"
))  # kỳ vọng: True

True
True
True

In [187]:
print(has_asymmetric_negation(
    "nước sôi ở 100 độ c",
    "nước sôi khi đun nóng đủ lâu"
))  # kỳ vọng: False

print(has_asymmetric_negation(
    "áp suất khí quyển giảm dần khi lên cao",
    "càng lên cao áp suất không khí càng thấp"
))  # kỳ vọng: False — chú ý: câu này có cụm "áp suất không khí", cần xác nhận hàm không bị nhầm "không" trong "không khí"

False
True

In [188]:
def has_asymmetric_negation(text1, text2):
    negation_words = ["không", "chẳng", "chả"]
    # Các từ ghép chứa "không"/"chẳng" nhưng KHÔNG mang nghĩa phủ định
    exception_words = ["không khí", "không gian", "không dây", "chẳng hạn"]
    
    def count_negation(text):
        text_copy = text
        for exc in exception_words:
            text_copy = text_copy.replace(exc, "")
        words = text_copy.split()
        return any(word in words for word in negation_words)
    
    text1_has_negation = count_negation(text1)
    text2_has_negation = count_negation(text2)
    
    return text1_has_negation != text2_has_negation

In [189]:
print(has_asymmetric_negation(
    "áp suất khí quyển giảm dần khi lên cao",
    "càng lên cao áp suất không khí càng thấp"
))  # kỳ vọng: False (sau khi sửa)

# Test lại các case cũ để đảm bảo không bị hỏng
print(has_asymmetric_negation(
    "nước sôi ở 100 độ c",
    "nước không sôi ở 100 độ c"
))  # kỳ vọng vẫn: True

False
True

In [190]:
antonym_pairs = [
    ("tăng", "giảm"),
    ("có", "không có"),
    ("đúng", "sai"),
    ("nhanh", "chậm"),
    ("nóng", "lạnh"),
    ("cao", "thấp"),
    ("lớn", "nhỏ"),
    ("nhiều", "ít"),
    ("trước", "sau"),
    ("trong", "ngoài"),
]

In [191]:
def has_antonym_conflict(text1, text2):
    words1 = set(text1.split())
    words2 = set(text2.split())
    
    for word_a, word_b in antonym_pairs:
        # Trường hợp: câu 1 có từ A, câu 2 có từ B (hoặc ngược lại) — dấu hiệu đối nghĩa
        if (word_a in words1 and word_b in words2) or (word_b in words1 and word_a in words2):
            return True
    
    return False

In [192]:
print(has_antonym_conflict(
    "áp suất khí quyển giảm dần khi lên cao",
    "áp suất khí quyển tăng dần khi lên cao"
))  # kỳ vọng: True

True

In [193]:
print(has_antonym_conflict(
    "nước sôi ở 100 độ c",
    "nước sôi khi đun nóng đủ lâu"
))  # kỳ vọng: False

False

In [194]:
def has_conflict_signal(text1, text2):
    return has_asymmetric_negation(text1, text2) or has_antonym_conflict(text1, text2)

In [195]:
def classify_with_conflict_check(ref_text, student_text, similarity_score,
                                   threshold_very_good=0.72, threshold_partial=0.40):
    # Bước 1: phân loại cơ bản theo ngưỡng (như Task 2)
    base_label = classify_by_threshold(similarity_score, threshold_very_good, threshold_partial)
    
    # Bước 2: kiểm tra tín hiệu xung đột (phủ định/đối nghĩa)
    conflict_detected = has_conflict_signal(ref_text, student_text)
    
    # Bước 3: nếu có xung đột VÀ nhãn cơ bản không phải "Not Related" → hạ xuống "Not Related"
    if conflict_detected and base_label != "Not Related":
        final_label = "Not Related"
    else:
        final_label = base_label
    
    return final_label, conflict_detected

In [196]:
results = []
for index, row in df.iterrows():
    label, conflict = classify_with_conflict_check(
        row['reference_text_clean'],
        row['student_answer_clean'],
        row['semantic_similarity']
    )
    results.append({'predicted_level_v3': label, 'conflict_detected': conflict})

results_df = pd.DataFrame(results)
df['predicted_level_v3'] = results_df['predicted_level_v3']
df['conflict_detected'] = results_df['conflict_detected']

In [197]:
df['is_correct_v3'] = df['expected_level'] == df['predicted_level_v3']
accuracy_v3 = df['is_correct_v3'].mean()

print(f"Accuracy chỉ dùng ngưỡng:              {df['is_correct'].mean():.2%}")
print(f"Accuracy + lớp kiểm tra xung đột:       {accuracy_v3:.2%}")

Accuracy chỉ dùng ngưỡng:              63.33%
Accuracy + lớp kiểm tra xung đột:       70.00%

In [198]:
saved_by_conflict_check = df[(df['conflict_detected'] == True) & (df['is_correct_v3'] == True) & (df['is_correct'] == False)]
saved_by_conflict_check[['reference_text', 'student_answer', 'expected_level', 'predicted_level', 'predicted_level_v3']]

,reference_text,student_answer,expected_level,predicted_level,predicted_level_v3
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related,Very Good,Not Related
15,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Không có lực nào giữa hai vật có khối lượng,Not Related,Partially Relevant,Not Related
22,Áp suất khí quyển giảm dần khi lên cao,Áp suất khí quyển tăng khi lên cao,Not Related,Very Good,Not Related
29,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim không tham gia vào việc vận chuyển máu,Not Related,Partially Relevant,Not Related

In [199]:
broken_by_conflict_check = df[(df['conflict_detected'] == True) & (df['is_correct_v3'] == False) & (df['is_correct'] == True)]
broken_by_conflict_check[['reference_text', 'student_answer', 'expected_level', 'predicted_level', 'predicted_level_v3']]

,reference_text,student_answer,expected_level,predicted_level,predicted_level_v3
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây không quang hợp vào ban đêm,Partially Relevant,Partially Relevant,Not Related
20,Áp suất khí quyển giảm dần khi lên cao,Càng lên cao áp suất không khí càng thấp,Very Good,Very Good,Not Related

In [200]:
def has_antonym_conflict(text1, text2):
    words1 = set(text1.split())
    words2 = set(text2.split())
    
    for word_a, word_b in antonym_pairs:
        # Chỉ báo xung đột nếu từ A CHỈ xuất hiện ở 1 câu, từ B CHỈ xuất hiện ở câu kia
        # (loại trừ trường hợp cả 2 từ cùng xuất hiện chung 1 câu — dấu hiệu mô tả quan hệ, không phải mâu thuẫn)
        case1 = (word_a in words1 and word_b in words2) and (word_b not in words1) and (word_a not in words2)
        case2 = (word_b in words1 and word_a in words2) and (word_a not in words1) and (word_b not in words2)
        if case1 or case2:
            return True
    
    return False

In [201]:
print(has_antonym_conflict(
    "áp suất khí quyển giảm dần khi lên cao",
    "càng lên cao áp suất không khí càng thấp"
))  # kỳ vọng: False (sau khi sửa)

False

In [202]:
print(has_antonym_conflict(
    "áp suất khí quyển giảm dần khi lên cao",
    "áp suất khí quyển tăng dần khi lên cao"
))  # kỳ vọng: True (vẫn đúng — chỉ có "tăng", không có "giảm" ở câu học sinh)

True

In [203]:
results = []
for index, row in df.iterrows():
    label, conflict = classify_with_conflict_check(
        row['reference_text_clean'],
        row['student_answer_clean'],
        row['semantic_similarity']
    )
    results.append({'predicted_level_v3': label, 'conflict_detected': conflict})

results_df = pd.DataFrame(results)
df['predicted_level_v3'] = results_df['predicted_level_v3']
df['conflict_detected'] = results_df['conflict_detected']

df['is_correct_v3'] = df['expected_level'] == df['predicted_level_v3']
accuracy_v3 = df['is_correct_v3'].mean()

print(f"Accuracy chỉ dùng ngưỡng:              {df['is_correct'].mean():.2%}")
print(f"Accuracy + lớp kiểm tra xung đột (v3):  {accuracy_v3:.2%}")

Accuracy chỉ dùng ngưỡng:              63.33%
Accuracy + lớp kiểm tra xung đột (v3):  73.33%

In [204]:
df[df.index.isin([7, 20])][['reference_text', 'student_answer', 'expected_level', 'predicted_level_v3', 'conflict_detected']]

,reference_text,student_answer,expected_level,predicted_level_v3,conflict_detected
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây không quang hợp vào ban đêm,Partially Relevant,Not Related,True
20,Áp suất khí quyển giảm dần khi lên cao,Càng lên cao áp suất không khí càng thấp,Very Good,Very Good,False

In [205]:
def is_empty_answer(text):
    if pd.isnull(text):
        return True
    return text.strip() == ""

In [206]:
print(is_empty_answer(""))           # True
print(is_empty_answer("   "))        # True
print(is_empty_answer(None))         # True
print(is_empty_answer(float('nan'))) # True
print(is_empty_answer("nước sôi"))   # False

True
True
True
True
False

In [207]:
def classify_answer(ref_text, student_text, threshold_very_good=0.72, threshold_partial=0.40):
    # Bước 1: kiểm tra câu trả lời trống trước tiên
    if is_empty_answer(student_text):
        return {
            "label": "Not Related",
            "similarity_score": 0.0,
            "conflict_detected": False,
            "reason": "Câu trả lời trống"
        }
    
    # Bước 2: tính semantic similarity
    similarity_score = compute_semantic_similarity(ref_text, student_text)
    
    # Bước 3: phân loại theo ngưỡng
    base_label = classify_by_threshold(similarity_score, threshold_very_good, threshold_partial)
    
    # Bước 4: kiểm tra xung đột (phủ định/đối nghĩa)
    conflict_detected = has_conflict_signal(ref_text, student_text)
    
    # Bước 5: hạ nhãn nếu phát hiện xung đột
    if conflict_detected and base_label != "Not Related":
        final_label = "Not Related"
        reason = "Phát hiện phủ định/đối nghĩa bất đối xứng, hạ nhãn để an toàn"
    else:
        final_label = base_label
        reason = None
    
    return {
        "label": final_label,
        "similarity_score": round(float(similarity_score), 4),
        "conflict_detected": conflict_detected,
        "reason": reason
    }

In [208]:
result1 = classify_answer(
    "Nước sôi ở 100 độ C tại áp suất khí quyển tiêu chuẩn",
    "Nước không sôi ở 100 độ C"
)
print(result1)

result2 = classify_answer(
    "Nước sôi ở 100 độ C tại áp suất khí quyển tiêu chuẩn",
    "Nước sôi ở 100 độ C khi áp suất bình thường"
)
print(result2)

result3 = classify_answer(
    "Nước sôi ở 100 độ C tại áp suất khí quyển tiêu chuẩn",
    ""
)
print(result3)

{'label': 'Not Related', 'similarity_score': 0.7985, 'conflict_detected': True, 'reason': 'Phát hiện phủ định/đối nghĩa bất đối xứng, hạ nhãn để an toàn'}
{'label': 'Very Good', 'similarity_score': 0.9737, 'conflict_detected': False, 'reason': None}
{'label': 'Not Related', 'similarity_score': 0.0, 'conflict_detected': False, 'reason': 'Câu trả lời trống'}

In [209]:
df.to_csv("test_data_step6.csv", index=False)

check = pd.read_csv("test_data_step6.csv", keep_default_na=False, na_values=[])
check.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        30 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  30 non-null     str
 5   tfidf_similarity      30 non-null     float64
 6   semantic_similarity   30 non-null     float64
 7   improvement           30 non-null     float64
 8   predicted_level       30 non-null     str
 9   is_correct            30 non-null     bool
 10  predicted_level_v2    30 non-null     str
 11  is_correct_v2         30 non-null     bool
 12  predicted_level_v3    30 non-null     str
 13  conflict_detected     30 non-null     bool
 14  is_correct_v3         30 non-null     bool
dtypes: bool(4), float64(3), str(8)
memory usage: 2.8 KB

In [210]:
import fitz
print(fitz.__doc__)

PyMuPDF 1.28.2: Python bindings for the MuPDF 1.28.2 library.
Python 3.12 running on darwin (64-bit).

In [211]:
import pymupdf

doc = pymupdf.open("pdftest.pdf")
print(f"Số trang: {len(doc)}")

Số trang: 4

In [212]:
for page_num, page in enumerate(doc):
    text = page.get_text()
    print(f"=== Trang {page_num + 1} (độ dài: {len(text)} ký tự) ===")
    print(text[:200])   # chỉ in 200 ký tự đầu mỗi trang để dễ nhìn
    print("...")
    print()

=== Trang 1 (độ dài: 1733 ký tự) ===
CÔNG NGHỆ THÔNG TIN TRONG KỶ NGUYÊN SỐ
Vai trò, xu hướng phát triển và tác động đối với xã hội
1. Giới thiệu về Công nghệ Thông tin
Công nghệ Thông tin (Information Technology – IT) là lĩnh vực liê
...

=== Trang 2 (độ dài: 2126 ký tự) ===
2.3. Cơ sở dữ liệu và dữ liệu lớn
Cơ sở dữ liệu giúp tổ chức lưu trữ và quản lý thông tin có cấu trúc. Khi số lượng dữ liệu tăng
nhanh, các kỹ thuật xử lý dữ liệu lớn trở nên quan trọng. Dữ liệu có
...

=== Trang 3 (độ dài: 2118 ký tự) ===
5. An toàn thông tin và bảo mật
Khi ngày càng nhiều hoạt động chuyển lên môi trường số, an toàn thông tin trở thành yêu cầu cơ
bản của mọi hệ thống. Một hệ thống an toàn cần bảo vệ tính bí mật, tính
...

=== Trang 4 (độ dài: 703 ký tự) ===
8. Kết luận
Công nghệ Thông tin đang giữ vai trò nền tảng trong quá trình chuyển đổi số. Từ phần mềm và
mạng máy tính đến AI, cloud computing và cybersecurity, mỗi lĩnh vực đều góp phần tạo ra các

...

In [213]:
print(repr(doc[0].get_text()[-300:]))   # 300 ký tự cuối của trang 1
print(repr(doc[1].get_text()[:300]))     # 300 ký tự đầu của trang 2

'ao đổi dữ liệu và sử dụng chung tài nguyên. Internet mở \nrộng khả năng kết nối trên phạm vi toàn cầu, tạo nền tảng cho website, thương mại điện tử, mạng \nxã hội và các dịch vụ trực tuyến. Trong doanh nghiệp, mạng nội bộ và các giải pháp bảo mật giúp \nnhân viên truy cập tài nguyên một cách an toàn. \n'
'2.3. Cơ sở dữ liệu và dữ liệu lớn \nCơ sở dữ liệu giúp tổ chức lưu trữ và quản lý thông tin có cấu trúc. Khi số lượng dữ liệu tăng \nnhanh, các kỹ thuật xử lý dữ liệu lớn trở nên quan trọng. Dữ liệu có thể được thu thập từ giao \ndịch, website, thiết bị IoT hoặc các ứng dụng. Nếu được quản lý tốt, dữ l'

In [214]:
sample = doc[1].get_text()[:300]
print("Trước clean:")
print(repr(sample))
print()
print("Sau clean:")
print(repr(clean_text(sample)))

Trước clean:
'2.3. Cơ sở dữ liệu và dữ liệu lớn \nCơ sở dữ liệu giúp tổ chức lưu trữ và quản lý thông tin có cấu trúc. Khi số lượng dữ liệu tăng \nnhanh, các kỹ thuật xử lý dữ liệu lớn trở nên quan trọng. Dữ liệu có thể được thu thập từ giao \ndịch, website, thiết bị IoT hoặc các ứng dụng. Nếu được quản lý tốt, dữ l'

Sau clean:
'23 cơ sở dữ liệu và dữ liệu lớn cơ sở dữ liệu giúp tổ chức lưu trữ và quản lý thông tin có cấu trúc khi số lượng dữ liệu tăng nhanh các kỹ thuật xử lý dữ liệu lớn trở nên quan trọng dữ liệu có thể được thu thập từ giao dịch website thiết bị iot hoặc các ứng dụng nếu được quản lý tốt dữ l'

In [215]:
def extract_pages_with_metadata(pdf_path):
    doc = pymupdf.open(pdf_path)
    pages_data = []
    
    for page_num, page in enumerate(doc):
        text = page.get_text()
        pages_data.append({
            "page_number": page_num + 1,
            "raw_text": text,
            "char_count": len(text)
        })
    
    doc.close()
    return pages_data

In [217]:
pages = extract_pages_with_metadata("pdftest.pdf")

for p in pages:
    print(f"Trang {p['page_number']}: {p['char_count']} ký tự")

Trang 1: 1733 ký tự
Trang 2: 2126 ký tự
Trang 3: 2118 ký tự
Trang 4: 703 ký tự

In [218]:
def extract_pages_with_metadata(pdf_path):
    doc = pymupdf.open(pdf_path)
    pages_data = []
    
    for page_num, page in enumerate(doc):
        raw = page.get_text()
        pages_data.append({
            "page_number": page_num + 1,
            "raw_text": raw,
            "clean_text": clean_text(raw),
            "char_count": len(raw)
        })
    
    doc.close()
    return pages_data

In [220]:
pages = extract_pages_with_metadata("pdftest.pdf")

print(pages[1]['raw_text'][:150])
print()
print(pages[1]['clean_text'][:150])

2.3. Cơ sở dữ liệu và dữ liệu lớn
Cơ sở dữ liệu giúp tổ chức lưu trữ và quản lý thông tin có cấu trúc. Khi số lượng dữ liệu tăng
nhanh, các kỹ thuật

23 cơ sở dữ liệu và dữ liệu lớn cơ sở dữ liệu giúp tổ chức lưu trữ và quản lý thông tin có cấu trúc khi số lượng dữ liệu tăng nhanh các kỹ thuật xử lý

In [221]:
def chunk_text(text, chunk_size=500, chunk_overlap=50):
    chunks = []
    start = 0
    text_length = len(text)
    
    while start < text_length:
        end = start + chunk_size
        chunk = text[start:end]
        chunks.append(chunk)
        
        start += chunk_size - chunk_overlap
    
    return chunks

In [222]:
test_text = "A" * 20 + "B" * 20 + "C" * 20   # 60 ký tự, dễ quan sát
test_chunks = chunk_text(test_text, chunk_size=30, chunk_overlap=10)

for i, c in enumerate(test_chunks):
    print(f"Chunk {i}: {c}")

Chunk 0: AAAAAAAAAAAAAAAAAAAABBBBBBBBBB
Chunk 1: BBBBBBBBBBBBBBBBBBBBCCCCCCCCCC
Chunk 2: CCCCCCCCCCCCCCCCCCCC

In [223]:
sample_chunks = chunk_text(pages[1]['clean_text'], chunk_size=500, chunk_overlap=50)

print(f"Số chunks tạo ra từ trang 2: {len(sample_chunks)}")
for i, c in enumerate(sample_chunks):
    print(f"--- Chunk {i} ({len(c)} ký tự) ---")
    print(c[:100], "...")
    print()

Số chunks tạo ra từ trang 2: 5
--- Chunk 0 (500 ký tự) ---
23 cơ sở dữ liệu và dữ liệu lớn cơ sở dữ liệu giúp tổ chức lưu trữ và quản lý thông tin có cấu trúc  ...

--- Chunk 1 (500 ký tự) ---
trong những hướng phát triển nổi bật của công nghệ thông tin ai hướng đến việc xây dựng các hệ thống ...

--- Chunk 2 (500 ký tự) ---
 các bài toán phức tạp những công nghệ này đang được ứng dụng trong gợi ý nội dung phát hiện gian lậ ...

--- Chunk 3 (500 ký tự) ---
ện toán đám mây và phát triển phần mềm điện toán đám mây cloud computing cho phép người dùng sử dụng ...

--- Chunk 4 (244 ký tự) ---
api giúp các ứng dụng trao đổi dữ liệu thông qua http các công nghệ như docker hỗ trợ đóng gói ứng d ...

In [224]:
no_overlap_chunks = chunk_text(pages[1]['clean_text'], chunk_size=500, chunk_overlap=0)
with_overlap_chunks = chunk_text(pages[1]['clean_text'], chunk_size=500, chunk_overlap=50)

print("=== KHÔNG có overlap — ranh giới chunk 0 và chunk 1 ===")
print("Cuối chunk 0:", no_overlap_chunks[0][-80:])
print("Đầu chunk 1:", no_overlap_chunks[1][:80])

print()
print("=== CÓ overlap — ranh giới chunk 0 và chunk 1 ===")
print("Cuối chunk 0:", with_overlap_chunks[0][-80:])
print("Đầu chunk 1:", with_overlap_chunks[1][:80])

=== KHÔNG có overlap — ranh giới chunk 0 và chunk 1 ===
Cuối chunk 0: cial intelligence – ai là một trong những hướng phát triển nổi bật của công nghệ
Đầu chunk 1:  thông tin ai hướng đến việc xây dựng các hệ thống có khả năng thực hiện những n

=== CÓ overlap — ranh giới chunk 0 và chunk 1 ===
Cuối chunk 0: cial intelligence – ai là một trong những hướng phát triển nổi bật của công nghệ
Đầu chunk 1: trong những hướng phát triển nổi bật của công nghệ thông tin ai hướng đến việc x

In [225]:
def create_chunks_with_metadata(pages_data, source_filename, chunk_size=500, chunk_overlap=50):
    all_chunks = []
    chunk_index = 0
    
    for page in pages_data:
        page_chunks = chunk_text(page['clean_text'], chunk_size, chunk_overlap)
        
        for c in page_chunks:
            all_chunks.append({
                "chunk_id": f"{source_filename}_chunk_{chunk_index}",
                "source_file": source_filename,
                "page_number": page['page_number'],
                "chunk_index": chunk_index,
                "text": c,
                "char_count": len(c)
            })
            chunk_index += 1
    
    return all_chunks

In [229]:
chunks = create_chunks_with_metadata(pages, "pdftest.pdf")

print(f"Tổng số chunks: {len(chunks)}")
print()
print(chunks[0])

Tổng số chunks: 16

{'chunk_id': 'pdftest.pdf_chunk_0', 'source_file': 'pdftest.pdf', 'page_number': 1, 'chunk_index': 0, 'text': 'công nghệ thông tin trong kỷ nguyên số vai trò xu hướng phát triển và tác động đối với xã hội 1 giới thiệu về công nghệ thông tin công nghệ thông tin information technology – it là lĩnh vực liên quan đến việc sử dụng máy tính phần mềm mạng truyền thông và các hệ thống dữ liệu để tạo ra lưu trữ xử lý truyền tải và bảo vệ thông tin trong xã hội hiện đại it không còn chỉ là công cụ hỗ trợ công việc văn phòng mà đã trở thành nền tảng của nhiều hoạt động kinh tế giáo dục y tế tài chính sản xuất và qu', 'char_count': 500}

In [227]:
def process_pdf_to_chunks(pdf_path, source_filename=None, chunk_size=500, chunk_overlap=50):
    if source_filename is None:
        import os
        source_filename = os.path.basename(pdf_path)
    
    pages_data = extract_pages_with_metadata(pdf_path)
    chunks = create_chunks_with_metadata(pages_data, source_filename, chunk_size, chunk_overlap)
    
    return chunks

In [230]:
final_chunks = process_pdf_to_chunks("pdftest.pdf")

print(f"Tổng số chunks: {len(final_chunks)}")
print()
print("Chunk đầu tiên:")
print(final_chunks[0])
print()
print("Chunk cuối cùng:")
print(final_chunks[-1])

Tổng số chunks: 16

Chunk đầu tiên:
{'chunk_id': 'pdftest.pdf_chunk_0', 'source_file': 'pdftest.pdf', 'page_number': 1, 'chunk_index': 0, 'text': 'công nghệ thông tin trong kỷ nguyên số vai trò xu hướng phát triển và tác động đối với xã hội 1 giới thiệu về công nghệ thông tin công nghệ thông tin information technology – it là lĩnh vực liên quan đến việc sử dụng máy tính phần mềm mạng truyền thông và các hệ thống dữ liệu để tạo ra lưu trữ xử lý truyền tải và bảo vệ thông tin trong xã hội hiện đại it không còn chỉ là công cụ hỗ trợ công việc văn phòng mà đã trở thành nền tảng của nhiều hoạt động kinh tế giáo dục y tế tài chính sản xuất và qu', 'char_count': 500}

Chunk cuối cùng:
{'chunk_id': 'pdftest.pdf_chunk_15', 'source_file': 'pdftest.pdf', 'page_number': 4, 'chunk_index': 15, 'text': ' cụ thể người học cần xây dựng nền tảng vững chắc biết cách tự học và có khả năng thích nghi với công nghệ mới đây là yếu tố quan trọng để có thể tham gia hiệu quả vào quá trình phát triển các sản phẩm và dịch vụ số trong tương lai', 'char_count': 231}

In [231]:
for c in final_chunks:
    print(f"[{c['chunk_id']}] (trang {c['page_number']}, {c['char_count']} ký tự)")
    print(f"  {c['text'][:80]}...")
    print()

[pdftest.pdf_chunk_0] (trang 1, 500 ký tự)
  công nghệ thông tin trong kỷ nguyên số vai trò xu hướng phát triển và tác động đ...

[pdftest.pdf_chunk_1] (trang 1, 500 ký tự)
  ộng kinh tế giáo dục y tế tài chính sản xuất và quản lý nhà nước sự phát triển c...

[pdftest.pdf_chunk_2] (trang 1, 500 ký tự)
  huận tiện hơn 2 các thành phần chính của công nghệ thông tin 21 phần cứng và phầ...

[pdftest.pdf_chunk_3] (trang 1, 311 ký tự)
  ho phép các thiết bị trao đổi dữ liệu và sử dụng chung tài nguyên internet mở rộ...

[pdftest.pdf_chunk_4] (trang 2, 500 ký tự)
  23 cơ sở dữ liệu và dữ liệu lớn cơ sở dữ liệu giúp tổ chức lưu trữ và quản lý th...

[pdftest.pdf_chunk_5] (trang 2, 500 ký tự)
  trong những hướng phát triển nổi bật của công nghệ thông tin ai hướng đến việc x...

[pdftest.pdf_chunk_6] (trang 2, 500 ký tự)
   các bài toán phức tạp những công nghệ này đang được ứng dụng trong gợi ý nội du...

[pdftest.pdf_chunk_7] (trang 2, 500 ký tự)
  ện toán đám mây và phát triển phần mềm điện toán đám mây cloud computing cho phé...

[pdftest.pdf_chunk_8] (trang 2, 244 ký tự)
  api giúp các ứng dụng trao đổi dữ liệu thông qua http các công nghệ như docker h...

[pdftest.pdf_chunk_9] (trang 3, 500 ký tự)
  5 an toàn thông tin và bảo mật khi ngày càng nhiều hoạt động chuyển lên môi trườ...

[pdftest.pdf_chunk_10] (trang 3, 500 ký tự)
  ách bảo vệ tài khoản nhận diện các liên kết đáng ngờ và không chia sẻ thông tin ...

[pdftest.pdf_chunk_11] (trang 3, 500 ký tự)
  ình ảnh mã nguồn và nhiều loại nội dung khác iot kết nối các cảm biến và thiết b...

[pdftest.pdf_chunk_12] (trang 3, 500 ký tự)
  7 vai trò của nguồn nhân lực it người làm công nghệ thông tin cần liên tục cập n...

[pdftest.pdf_chunk_13] (trang 3, 236 ký tự)
   người học hiểu quy trình từ phân tích yêu cầu thiết kế cơ sở dữ liệu xây dựng a...

[pdftest.pdf_chunk_14] (trang 4, 500 ký tự)
  8 kết luận công nghệ thông tin đang giữ vai trò nền tảng trong quá trình chuyển ...

[pdftest.pdf_chunk_15] (trang 4, 231 ký tự)
   cụ thể người học cần xây dựng nền tảng vững chắc biết cách tự học và có khả năn...

In [232]:
import json

with open("chunks_output.json", "w", encoding="utf-8") as f:
    json.dump(final_chunks, f, ensure_ascii=False, indent=2)

print("Đã lưu file chunks_output.json")

Đã lưu file chunks_output.json

In [233]:
with open("chunks_output.json", "r", encoding="utf-8") as f:
    loaded_chunks = json.load(f)

print(f"Số chunks đọc lại từ file: {len(loaded_chunks)}")
print(loaded_chunks[0])

Số chunks đọc lại từ file: 16
{'chunk_id': 'pdftest.pdf_chunk_0', 'source_file': 'pdftest.pdf', 'page_number': 1, 'chunk_index': 0, 'text': 'công nghệ thông tin trong kỷ nguyên số vai trò xu hướng phát triển và tác động đối với xã hội 1 giới thiệu về công nghệ thông tin công nghệ thông tin information technology – it là lĩnh vực liên quan đến việc sử dụng máy tính phần mềm mạng truyền thông và các hệ thống dữ liệu để tạo ra lưu trữ xử lý truyền tải và bảo vệ thông tin trong xã hội hiện đại it không còn chỉ là công cụ hỗ trợ công việc văn phòng mà đã trở thành nền tảng của nhiều hoạt động kinh tế giáo dục y tế tài chính sản xuất và qu', 'char_count': 500}

In [234]:
import chromadb
print(chromadb.__version__)

1.5.9

In [235]:
import chromadb

chroma_client = chromadb.PersistentClient(path="./chroma_db")

In [236]:
collection = chroma_client.get_or_create_collection(name="giao_an_collection")

In [237]:
print(collection.name)
print(collection.count())

giao_an_collection
0

In [238]:
def encode_texts_for_chroma(texts):
    embeddings = model.encode(texts)
    return embeddings.tolist()

In [239]:
test_embeddings = encode_texts_for_chroma(["nước sôi ở 100 độ c", "trái đất quay quanh mặt trời"])
print(len(test_embeddings))        # kỳ vọng: 2 (số câu)
print(len(test_embeddings[0]))     # kỳ vọng: 384 (số chiều mỗi vector)
print(type(test_embeddings[0]))    # kỳ vọng: <class 'list'>

2
384
<class 'list'>

In [240]:
ids = [c['chunk_id'] for c in final_chunks]
documents = [c['text'] for c in final_chunks]
metadatas = [
    {
        "source_file": c['source_file'],
        "page_number": c['page_number'],
        "chunk_index": c['chunk_index']
    }
    for c in final_chunks
]

print(f"Số lượng ids: {len(ids)}")
print(f"Số lượng documents: {len(documents)}")
print(f"Số lượng metadatas: {len(metadatas)}")

Số lượng ids: 16
Số lượng documents: 16
Số lượng metadatas: 16

In [241]:
embeddings = encode_texts_for_chroma(documents)
print(len(embeddings))

16

In [242]:
collection.add(
    ids=ids,
    documents=documents,
    embeddings=embeddings,
    metadatas=metadatas
)

print(f"Đã thêm {collection.count()} items vào collection")

Đã thêm 16 items vào collection

In [243]:
print(collection.count())

16

In [244]:
result = collection.get(ids=["pdftest.pdf_chunk_0", "pdftest.pdf_chunk_5"])
print(result)

{'ids': ['pdftest.pdf_chunk_0', 'pdftest.pdf_chunk_5'], 'embeddings': None, 'documents': ['công nghệ thông tin trong kỷ nguyên số vai trò xu hướng phát triển và tác động đối với xã hội 1 giới thiệu về công nghệ thông tin công nghệ thông tin information technology – it là lĩnh vực liên quan đến việc sử dụng máy tính phần mềm mạng truyền thông và các hệ thống dữ liệu để tạo ra lưu trữ xử lý truyền tải và bảo vệ thông tin trong xã hội hiện đại it không còn chỉ là công cụ hỗ trợ công việc văn phòng mà đã trở thành nền tảng của nhiều hoạt động kinh tế giáo dục y tế tài chính sản xuất và qu', 'trong những hướng phát triển nổi bật của công nghệ thông tin ai hướng đến việc xây dựng các hệ thống có khả năng thực hiện những nhiệm vụ thường cần đến trí thông minh của con người chẳng hạn như nhận dạng hình ảnh hiểu ngôn ngữ dự đoán và hỗ trợ ra quyết định machine learning ml là một nhánh của ai trong đó hệ thống học các mẫu từ dữ liệu để đưa ra dự đoán hoặc quyết định deep learning dl là một hướng của ml sử dụng mạng nơron nhiều lớp để xử lý các bài toán phức tạp những công nghệ này đang đư'], 'uris': None, 'included': ['metadatas', 'documents'], 'data': None, 'metadatas': [{'chunk_index': 0, 'page_number': 1, 'source_file': 'pdftest.pdf'}, {'page_number': 2, 'source_file': 'pdftest.pdf', 'chunk_index': 5}]}

In [245]:
all_items = collection.get()
for i in range(len(all_items['ids'])):
    print(f"ID: {all_items['ids'][i]}")
    print(f"  Trang: {all_items['metadatas'][i]['page_number']}")
    print(f"  Text: {all_items['documents'][i][:60]}...")
    print()

ID: pdftest.pdf_chunk_0
  Trang: 1
  Text: công nghệ thông tin trong kỷ nguyên số vai trò xu hướng phát...

ID: pdftest.pdf_chunk_1
  Trang: 1
  Text: ộng kinh tế giáo dục y tế tài chính sản xuất và quản lý nhà ...

ID: pdftest.pdf_chunk_2
  Trang: 1
  Text: huận tiện hơn 2 các thành phần chính của công nghệ thông tin...

ID: pdftest.pdf_chunk_3
  Trang: 1
  Text: ho phép các thiết bị trao đổi dữ liệu và sử dụng chung tài n...

ID: pdftest.pdf_chunk_4
  Trang: 2
  Text: 23 cơ sở dữ liệu và dữ liệu lớn cơ sở dữ liệu giúp tổ chức l...

ID: pdftest.pdf_chunk_5
  Trang: 2
  Text: trong những hướng phát triển nổi bật của công nghệ thông tin...

ID: pdftest.pdf_chunk_6
  Trang: 2
  Text:  các bài toán phức tạp những công nghệ này đang được ứng dụn...

ID: pdftest.pdf_chunk_7
  Trang: 2
  Text: ện toán đám mây và phát triển phần mềm điện toán đám mây clo...

ID: pdftest.pdf_chunk_8
  Trang: 2
  Text: api giúp các ứng dụng trao đổi dữ liệu thông qua http các cô...

ID: pdftest.pdf_chunk_9
  Trang: 3
  Text: 5 an toàn thông tin và bảo mật khi ngày càng nhiều hoạt động...

ID: pdftest.pdf_chunk_10
  Trang: 3
  Text: ách bảo vệ tài khoản nhận diện các liên kết đáng ngờ và khôn...

ID: pdftest.pdf_chunk_11
  Trang: 3
  Text: ình ảnh mã nguồn và nhiều loại nội dung khác iot kết nối các...

ID: pdftest.pdf_chunk_12
  Trang: 3
  Text: 7 vai trò của nguồn nhân lực it người làm công nghệ thông ti...

ID: pdftest.pdf_chunk_13
  Trang: 3
  Text:  người học hiểu quy trình từ phân tích yêu cầu thiết kế cơ s...

ID: pdftest.pdf_chunk_14
  Trang: 4
  Text: 8 kết luận công nghệ thông tin đang giữ vai trò nền tảng tro...

ID: pdftest.pdf_chunk_15
  Trang: 4
  Text:  cụ thể người học cần xây dựng nền tảng vững chắc biết cách ...

In [246]:
query_text = "trí tuệ nhân tạo là gì"
query_embedding = model.encode([query_text]).tolist()

results = collection.query(
    query_embeddings=query_embedding,
    n_results=3
)

print(results)

{'ids': [['pdftest.pdf_chunk_5', 'pdftest.pdf_chunk_11', 'pdftest.pdf_chunk_1']], 'embeddings': None, 'documents': [['trong những hướng phát triển nổi bật của công nghệ thông tin ai hướng đến việc xây dựng các hệ thống có khả năng thực hiện những nhiệm vụ thường cần đến trí thông minh của con người chẳng hạn như nhận dạng hình ảnh hiểu ngôn ngữ dự đoán và hỗ trợ ra quyết định machine learning ml là một nhánh của ai trong đó hệ thống học các mẫu từ dữ liệu để đưa ra dự đoán hoặc quyết định deep learning dl là một hướng của ml sử dụng mạng nơron nhiều lớp để xử lý các bài toán phức tạp những công nghệ này đang đư', 'ình ảnh mã nguồn và nhiều loại nội dung khác iot kết nối các cảm biến và thiết bị vật lý với internet tạo ra lượng dữ liệu lớn cho các hệ thống thông minh một xu hướng quan trọng khác là sự kết hợp giữa it và các lĩnh vực chuyên môn ví dụ healthtech ứng dụng công nghệ vào y tế fintech ứng dụng it vào tài chính còn edtech sử dụng công nghệ để hỗ trợ giáo dục điều này làm tăng nhu cầu về nhân lực vừa có kỹ năng kỹ thuật vừa hiểu lĩnh vực nghiệp vụ 7 vai trò của nguồn nhân lực it người làm công ngh', 'ộng kinh tế giáo dục y tế tài chính sản xuất và quản lý nhà nước sự phát triển của internet điện toán đám mây trí tuệ nhân tạo và các thiết bị thông minh đang làm thay đổi cách con người làm việc và giao tiếp một doanh nghiệp có thể vận hành hệ thống trên nền tảng đám mây phân tích dữ liệu để đưa ra quyết định và sử dụng ai để tự động hóa nhiều nhiệm vụ đối với cá nhân các dịch vụ trực tuyến giúp việc học tập mua sắm giải trí và kết nối trở nên thuận tiện hơn 2 các thành phần chính của công nghệ']], 'uris': None, 'included': ['metadatas', 'documents', 'distances'], 'data': None, 'metadatas': [[{'chunk_index': 5, 'source_file': 'pdftest.pdf', 'page_number': 2}, {'chunk_index': 11, 'source_file': 'pdftest.pdf', 'page_number': 3}, {'source_file': 'pdftest.pdf', 'chunk_index': 1, 'page_number': 1}]], 'distances': [[14.110380172729492, 15.425154685974121, 15.67569351196289]]}

In [247]:
for i in range(len(results['ids'][0])):
    print(f"Rank {i+1}:")
    print(f"  Chunk ID: {results['ids'][0][i]}")
    print(f"  Trang: {results['metadatas'][0][i]['page_number']}")
    print(f"  Distance: {results['distances'][0][i]:.4f}")
    print(f"  Text: {results['documents'][0][i][:100]}...")
    print()

Rank 1:
  Chunk ID: pdftest.pdf_chunk_5
  Trang: 2
  Distance: 14.1104
  Text: trong những hướng phát triển nổi bật của công nghệ thông tin ai hướng đến việc xây dựng các hệ thống...

Rank 2:
  Chunk ID: pdftest.pdf_chunk_11
  Trang: 3
  Distance: 15.4252
  Text: ình ảnh mã nguồn và nhiều loại nội dung khác iot kết nối các cảm biến và thiết bị vật lý với interne...

Rank 3:
  Chunk ID: pdftest.pdf_chunk_1
  Trang: 1
  Distance: 15.6757
  Text: ộng kinh tế giáo dục y tế tài chính sản xuất và quản lý nhà nước sự phát triển của internet điện toá...

In [248]:
distance = results['distances'][0][0]
approx_similarity = 1 - distance
print(f"Distance: {distance:.4f} → Similarity ước lượng: {approx_similarity:.4f}")

Distance: 14.1104 → Similarity ước lượng: -13.1104

In [249]:
chroma_client.delete_collection(name="giao_an_collection")

collection = chroma_client.get_or_create_collection(
    name="giao_an_collection",
    metadata={"hnsw:space": "cosine"}
)

print(collection.count())

0

In [250]:
collection.add(
    ids=ids,
    documents=documents,
    embeddings=embeddings,
    metadatas=metadatas
)

print(f"Đã thêm lại {collection.count()} items")

Đã thêm lại 16 items

In [251]:
query_text = "trí tuệ nhân tạo là gì"
query_embedding = model.encode([query_text]).tolist()

results = collection.query(
    query_embeddings=query_embedding,
    n_results=3
)

for i in range(len(results['ids'][0])):
    distance = results['distances'][0][i]
    similarity = 1 - distance
    print(f"Rank {i+1}: {results['ids'][0][i]} | Distance: {distance:.4f} | Similarity: {similarity:.4f}")

Rank 1: pdftest.pdf_chunk_5 | Distance: 0.4320 | Similarity: 0.5680
Rank 2: pdftest.pdf_chunk_1 | Distance: 0.4771 | Similarity: 0.5229
Rank 3: pdftest.pdf_chunk_11 | Distance: 0.4839 | Similarity: 0.5161

In [252]:
new_client = chromadb.PersistentClient(path="./chroma_db")
new_collection = new_client.get_or_create_collection(
    name="giao_an_collection",
    metadata={"hnsw:space": "cosine"}
)

print(f"Số lượng items đọc lại: {new_collection.count()}")

Số lượng items đọc lại: 16

In [253]:
import chromadb
chroma_client = chromadb.PersistentClient(path="./chroma_db")
collection = chroma_client.get_or_create_collection(
    name="giao_an_collection",
    metadata={"hnsw:space": "cosine"}
)
print(collection.count())

16

In [254]:
try:
    collection.add(
        ids=["pdftest.pdf_chunk_0"],
        documents=["nội dung test trùng lặp"],
        embeddings=model.encode(["nội dung test trùng lặp"]).tolist(),
        metadatas=[{"source_file": "test.pdf", "page_number": 1, "chunk_index": 0}]
    )
except Exception as e:
    print(f"Lỗi: {e}")

In [255]:
collection.upsert(
    ids=["pdftest.pdf_chunk_0"],
    documents=["nội dung test trùng lặp"],
    embeddings=model.encode(["nội dung test trùng lặp"]).tolist(),
    metadatas=[{"source_file": "test.pdf", "page_number": 1, "chunk_index": 0}]
)

result = collection.get(ids=["pdftest.pdf_chunk_0"])
print(result['documents'])

['nội dung test trùng lặp']

In [256]:
collection.upsert(
    ids=[final_chunks[0]['chunk_id']],
    documents=[final_chunks[0]['text']],
    embeddings=model.encode([final_chunks[0]['text']]).tolist(),
    metadatas=[{
        "source_file": final_chunks[0]['source_file'],
        "page_number": final_chunks[0]['page_number'],
        "chunk_index": final_chunks[0]['chunk_index']
    }]
)
print("Đã khôi phục dữ liệu gốc")

Đã khôi phục dữ liệu gốc

In [257]:
def add_document_to_db(chunks, collection, model):
    ids = [c['chunk_id'] for c in chunks]
    documents = [c['text'] for c in chunks]
    metadatas = [
        {
            "source_file": c['source_file'],
            "page_number": c['page_number'],
            "chunk_index": c['chunk_index']
        }
        for c in chunks
    ]

    embeddings = model.encode(documents).tolist()

    collection.upsert(
        ids=ids,
        documents=documents,
        embeddings=embeddings,
        metadatas=metadatas
    )

    return {
        "status": "success",
        "chunks_added": len(chunks),
        "total_in_collection": collection.count()
    }

In [258]:
new_chunks = process_pdf_to_chunks("pdftest.pdf")
result = add_document_to_db(new_chunks, collection, model)
print(result)

{'status': 'success', 'chunks_added': 16, 'total_in_collection': 16}

In [259]:
test_vec = model.encode("kiểm tra model còn hoạt động")
print(test_vec.shape)

(384,)

In [260]:
print(collection.count())

16

In [261]:
test_result = classify_answer(
    "Nước sôi ở 100 độ C tại áp suất khí quyển tiêu chuẩn",
    "Nước sôi ở 100 độ C khi áp suất bình thường"
)
print(test_result)

{'label': 'Very Good', 'similarity_score': 0.9737, 'conflict_detected': False, 'reason': None}

In [262]:
def retrieve_relevant_chunks(student_answer, collection, model, top_k=3):
    query_embedding = model.encode([student_answer]).tolist()
    
    results = collection.query(
        query_embeddings=query_embedding,
        n_results=top_k
    )
    
    chunks = []
    for i in range(len(results['ids'][0])):
        distance = results['distances'][0][i]
        similarity = 1 - distance
        chunks.append({
            "chunk_id": results['ids'][0][i],
            "text": results['documents'][0][i],
            "similarity": round(similarity, 4),
            "page_number": results['metadatas'][0][i]['page_number'],
            "source_file": results['metadatas'][0][i]['source_file']
        })
    
    return chunks

In [263]:
chunks = retrieve_relevant_chunks("machine learning là gì", collection, model, top_k=3)

for c in chunks:
    print(f"[{c['chunk_id']}] Trang {c['page_number']} | Similarity: {c['similarity']}")
    print(f"  {c['text'][:100]}...")
    print()

[pdftest.pdf_chunk_5] Trang 2 | Similarity: 0.6987
  trong những hướng phát triển nổi bật của công nghệ thông tin ai hướng đến việc xây dựng các hệ thống...

[pdftest.pdf_chunk_1] Trang 1 | Similarity: 0.4701
  ộng kinh tế giáo dục y tế tài chính sản xuất và quản lý nhà nước sự phát triển của internet điện toá...

[pdftest.pdf_chunk_14] Trang 4 | Similarity: 0.4408
  8 kết luận công nghệ thông tin đang giữ vai trò nền tảng trong quá trình chuyển đổi số từ phần mềm v...

In [264]:
chunks_unrelated = retrieve_relevant_chunks("cách nấu phở bò truyền thống", collection, model, top_k=3)

for c in chunks_unrelated:
    print(f"[{c['chunk_id']}] Similarity: {c['similarity']}")

[pdftest.pdf_chunk_15] Similarity: 0.1036
[pdftest.pdf_chunk_5] Similarity: 0.0997
[pdftest.pdf_chunk_13] Similarity: 0.0823

In [265]:
chunks = retrieve_relevant_chunks("trí tuệ nhân tạo và học máy", collection, model, top_k=3)
for i, c in enumerate(chunks):
    print(f"Rank {i+1}: similarity = {c['similarity']}")

Rank 1: similarity = 0.6599
Rank 2: similarity = 0.6305
Rank 3: similarity = 0.6006

In [266]:
def get_best_reference_text(student_answer, collection, model, top_k=3):
    chunks = retrieve_relevant_chunks(student_answer, collection, model, top_k)
    
    if not chunks:
        return None
    
    best_chunk = chunks[0]
    return best_chunk

In [ ]:
def classify_answer(ref_text, student_text, threshold_very_good=0.72, threshold_partial=0.40):

In [268]:
chunks = retrieve_relevant_chunks("trí tuệ nhân tạo và học máy", collection, model, top_k=1)
best_chunk_text = chunks[0]['text']

result = classify_answer(best_chunk_text, "AI là công nghệ giúp máy tính học từ dữ liệu để đưa ra dự đoán")
print(result)

None

In [271]:
def evaluate_essay_answer(student_answer, collection, model, top_k=3, 
                            threshold_very_good=0.72, threshold_partial=0.40,
                            min_relevance_threshold=0.30):
    # Bước 1: kiểm tra câu trả lời trống trước tiên
    if is_empty_answer(student_answer):
        return {
            "label": "Not Related",
            "similarity_score": 0.0,
            "conflict_detected": False,
            "reason": "Câu trả lời trống",
            "reference_chunks": []
        }
    
    # Bước 2: truy vấn top chunks liên quan
    chunks = retrieve_relevant_chunks(student_answer, collection, model, top_k)
    
    # Bước 3: kiểm tra có tìm được chunk nào đủ liên quan không
    if not chunks or chunks[0]['similarity'] < min_relevance_threshold:
        return {
            "label": "Not Related",
            "similarity_score": chunks[0]['similarity'] if chunks else 0.0,
            "conflict_detected": False,
            "reason": "Không tìm thấy nội dung đủ liên quan trong tài liệu tham khảo",
            "reference_chunks": chunks
        }
    
    # Bước 4: dùng chunk liên quan nhất để chấm điểm qua classify_answer()
    best_chunk = chunks[0]
    classification = classify_answer(
        best_chunk['text'], 
        student_answer, 
        threshold_very_good, 
        threshold_partial
    )
    
    # Bước 5: đính kèm thông tin nguồn tham khảo vào kết quả cuối
    classification['reference_chunks'] = chunks
    classification['primary_source'] = {
        "page_number": best_chunk['page_number'],
        "source_file": best_chunk['source_file']
    }
    
    return classification

In [273]:
import inspect
print(inspect.getsource(classify_answer))

def classify_answer(ref_text, student_text, threshold_very_good=0.72, threshold_partial=0.40):
    ...

In [275]:
def classify_answer(ref_text, student_text, threshold_very_good=0.72, threshold_partial=0.40):
    if is_empty_answer(student_text):
        return {
            "label": "Not Related",
            "similarity_score": 0.0,
            "conflict_detected": False,
            "reason": "Câu trả lời trống"
        }
    
    similarity_score = compute_semantic_similarity(ref_text, student_text)
    base_label = classify_by_threshold(similarity_score, threshold_very_good, threshold_partial)
    conflict_detected = has_conflict_signal(ref_text, student_text)
    
    if conflict_detected and base_label != "Not Related":
        final_label = "Not Related"
        reason = "Phát hiện phủ định/đối nghĩa bất đối xứng, hạ nhãn để an toàn"
    else:
        final_label = base_label
        reason = None
    
    return {
        "label": final_label,
        "similarity_score": round(float(similarity_score), 4),
        "conflict_detected": conflict_detected,
        "reason": reason
    }

In [276]:
test_result = classify_answer(
    "Nước sôi ở 100 độ C tại áp suất khí quyển tiêu chuẩn",
    "Nước sôi ở 100 độ C khi áp suất bình thường"
)
print(test_result)

{'label': 'Very Good', 'similarity_score': 0.9737, 'conflict_detected': False, 'reason': None}

In [277]:
chunks = retrieve_relevant_chunks("trí tuệ nhân tạo và học máy", collection, model, top_k=1)
best_chunk_text = chunks[0]['text']

result = classify_answer(best_chunk_text, "AI là công nghệ giúp máy tính học từ dữ liệu để đưa ra dự đoán")
print(result)

{'label': 'Partially Relevant', 'similarity_score': 0.5366, 'conflict_detected': False, 'reason': None}

In [278]:
result1 = evaluate_essay_answer(
    "AI là công nghệ giúp máy tính học từ dữ liệu để đưa ra dự đoán và quyết định",
    collection, model
)
print(result1)

{'label': 'Partially Relevant', 'similarity_score': 0.6495, 'conflict_detected': False, 'reason': None, 'reference_chunks': [{'chunk_id': 'pdftest.pdf_chunk_5', 'text': 'trong những hướng phát triển nổi bật của công nghệ thông tin ai hướng đến việc xây dựng các hệ thống có khả năng thực hiện những nhiệm vụ thường cần đến trí thông minh của con người chẳng hạn như nhận dạng hình ảnh hiểu ngôn ngữ dự đoán và hỗ trợ ra quyết định machine learning ml là một nhánh của ai trong đó hệ thống học các mẫu từ dữ liệu để đưa ra dự đoán hoặc quyết định deep learning dl là một hướng của ml sử dụng mạng nơron nhiều lớp để xử lý các bài toán phức tạp những công nghệ này đang đư', 'similarity': 0.6495, 'page_number': 2, 'source_file': 'pdftest.pdf'}, {'chunk_id': 'pdftest.pdf_chunk_1', 'text': 'ộng kinh tế giáo dục y tế tài chính sản xuất và quản lý nhà nước sự phát triển của internet điện toán đám mây trí tuệ nhân tạo và các thiết bị thông minh đang làm thay đổi cách con người làm việc và giao tiếp một doanh nghiệp có thể vận hành hệ thống trên nền tảng đám mây phân tích dữ liệu để đưa ra quyết định và sử dụng ai để tự động hóa nhiều nhiệm vụ đối với cá nhân các dịch vụ trực tuyến giúp việc học tập mua sắm giải trí và kết nối trở nên thuận tiện hơn 2 các thành phần chính của công nghệ', 'similarity': 0.5438, 'page_number': 1, 'source_file': 'pdftest.pdf'}, {'chunk_id': 'pdftest.pdf_chunk_11', 'text': 'ình ảnh mã nguồn và nhiều loại nội dung khác iot kết nối các cảm biến và thiết bị vật lý với internet tạo ra lượng dữ liệu lớn cho các hệ thống thông minh một xu hướng quan trọng khác là sự kết hợp giữa it và các lĩnh vực chuyên môn ví dụ healthtech ứng dụng công nghệ vào y tế fintech ứng dụng it vào tài chính còn edtech sử dụng công nghệ để hỗ trợ giáo dục điều này làm tăng nhu cầu về nhân lực vừa có kỹ năng kỹ thuật vừa hiểu lĩnh vực nghiệp vụ 7 vai trò của nguồn nhân lực it người làm công ngh', 'similarity': 0.5404, 'page_number': 3, 'source_file': 'pdftest.pdf'}], 'primary_source': {'page_number': 2, 'source_file': 'pdftest.pdf'}}

In [279]:
result2 = evaluate_essay_answer(
    "Trí tuệ nhân tạo AI hướng đến xây dựng hệ thống có khả năng làm việc như con người, "
    "chẳng hạn nhận dạng hình ảnh, hiểu ngôn ngữ, dự đoán. Machine Learning là nhánh của AI "
    "giúp hệ thống học từ dữ liệu để đưa ra dự đoán.",
    collection, model
)
print(f"Label: {result2['label']}, Similarity: {result2['similarity_score']}")

Label: Very Good, Similarity: 0.729

In [280]:
result3 = evaluate_essay_answer(
    "Máy tính là thiết bị dùng để chơi game và xem phim giải trí",
    collection, model
)
print(f"Label: {result3['label']}, Similarity: {result3['similarity_score']}")

Label: Partially Relevant, Similarity: 0.5439

In [281]:
result4 = evaluate_essay_answer(
    "Điện toán đám mây giúp doanh nghiệp không cần đầu tư hạ tầng vật lý",
    collection, model
)
print(f"Label: {result4['label']}, Similarity: {result4['similarity_score']}")
print(f"Trang tham khảo: {result4['primary_source']['page_number']}")

Label: Not Related, Similarity: 0.7518
Trang tham khảo: 2

In [282]:
result5 = evaluate_essay_answer(
    "Cách nấu phở bò truyền thống cần những nguyên liệu gì",
    collection, model
)
print(result5)

{'label': 'Not Related', 'similarity_score': 0.1794, 'conflict_detected': False, 'reason': 'Không tìm thấy nội dung đủ liên quan trong tài liệu tham khảo', 'reference_chunks': [{'chunk_id': 'pdftest.pdf_chunk_15', 'text': ' cụ thể người học cần xây dựng nền tảng vững chắc biết cách tự học và có khả năng thích nghi với công nghệ mới đây là yếu tố quan trọng để có thể tham gia hiệu quả vào quá trình phát triển các sản phẩm và dịch vụ số trong tương lai', 'similarity': 0.1794, 'page_number': 4, 'source_file': 'pdftest.pdf'}, {'chunk_id': 'pdftest.pdf_chunk_6', 'text': ' các bài toán phức tạp những công nghệ này đang được ứng dụng trong gợi ý nội dung phát hiện gian lận nhận diện hình ảnh xử lý ngôn ngữ tự nhiên và nhiều sản phẩm phần mềm hiện đại tuy nhiên ai không phải là giải pháp phù hợp cho mọi bài toán chất lượng dữ liệu khả năng giải thích kết quả chi phí tính toán và vấn đề bảo mật đều cần được xem xét vì vậy người phát triển cần hiểu cả công nghệ lẫn bối cảnh nghiệp vụ trước khi đưa ai vào sản phẩm 4 điện toán đám mây và phát triển phần mềm điện toán đ', 'similarity': 0.1517, 'page_number': 2, 'source_file': 'pdftest.pdf'}, {'chunk_id': 'pdftest.pdf_chunk_5', 'text': 'trong những hướng phát triển nổi bật của công nghệ thông tin ai hướng đến việc xây dựng các hệ thống có khả năng thực hiện những nhiệm vụ thường cần đến trí thông minh của con người chẳng hạn như nhận dạng hình ảnh hiểu ngôn ngữ dự đoán và hỗ trợ ra quyết định machine learning ml là một nhánh của ai trong đó hệ thống học các mẫu từ dữ liệu để đưa ra dự đoán hoặc quyết định deep learning dl là một hướng của ml sử dụng mạng nơron nhiều lớp để xử lý các bài toán phức tạp những công nghệ này đang đư', 'similarity': 0.1347, 'page_number': 2, 'source_file': 'pdftest.pdf'}]}

In [283]:
best_chunk = retrieve_relevant_chunks(
    "Điện toán đám mây giúp doanh nghiệp không cần đầu tư hạ tầng vật lý",
    collection, model, top_k=1
)[0]

print(has_asymmetric_negation(
    best_chunk['text'],
    "Điện toán đám mây giúp doanh nghiệp không cần đầu tư hạ tầng vật lý"
))
print()
print(best_chunk['text'])

True

ện toán đám mây và phát triển phần mềm điện toán đám mây cloud computing cho phép người dùng sử dụng tài nguyên máy chủ lưu trữ và các dịch vụ phần mềm thông qua internet thay vì phải đầu tư toàn bộ hạ tầng vật lý doanh nghiệp có thể thuê tài nguyên theo nhu cầu điều này giúp giảm chi phí ban đầu và tăng khả năng mở rộng của hệ thống trong phát triển phần mềm hiện nay các kiến trúc như clientserver microservices và api được sử dụng rộng rãi rest api giúp các ứng dụng trao đổi dữ liệu thông qua h

In [284]:
exception_words = ["không khí", "không gian", "không dây", "chẳng hạn"]

In [285]:
negation_words = ["không", "chẳng", "chả"]
exception_words = ["không khí", "không gian", "không dây", "chẳng hạn"]

text1 = best_chunk['text']
text2 = "điện toán đám mây giúp doanh nghiệp không cần đầu tư hạ tầng vật lý"

def debug_negation(text):
    text_copy = text
    for exc in exception_words:
        text_copy = text_copy.replace(exc, "")
    words = text_copy.split()
    found = [w for w in words if w in negation_words]
    return found

print("Text1 (chunk) - từ phủ định tìm thấy:", debug_negation(text1))
print("Text2 (student) - từ phủ định tìm thấy:", debug_negation(text2))

Text1 (chunk) - từ phủ định tìm thấy: []
Text2 (student) - từ phủ định tìm thấy: ['không']

In [286]:
def evaluate_essay_answer(student_answer, collection, model, top_k=3, 
                            threshold_very_good=0.72, threshold_partial=0.40,
                            min_relevance_threshold=0.30):
    if is_empty_answer(student_answer):
        return {
            "label": "Not Related",
            "similarity_score": 0.0,
            "conflict_detected": False,
            "reason": "Câu trả lời trống",
            "reference_chunks": []
        }
    
    chunks = retrieve_relevant_chunks(student_answer, collection, model, top_k)
    
    if not chunks or chunks[0]['similarity'] < min_relevance_threshold:
        return {
            "label": "Not Related",
            "similarity_score": chunks[0]['similarity'] if chunks else 0.0,
            "conflict_detected": False,
            "reason": "Không tìm thấy nội dung đủ liên quan trong tài liệu tham khảo",
            "reference_chunks": chunks
        }
    
    best_chunk = chunks[0]
    
    # Không dùng classify_answer() (có kiểm tra xung đột) — chỉ dùng ngưỡng thuần túy
    similarity_score = best_chunk['similarity']
    label = classify_by_threshold(similarity_score, threshold_very_good, threshold_partial)
    
    return {
        "label": label,
        "similarity_score": round(float(similarity_score), 4),
        "conflict_detected": None,
        "reason": "Lớp kiểm tra phủ định không áp dụng cho tài liệu dài (độ tin cậy thấp)",
        "reference_chunks": chunks,
        "primary_source": {
            "page_number": best_chunk['page_number'],
            "source_file": best_chunk['source_file']
        }
    }

In [287]:
result3_fixed = evaluate_essay_answer(
    "Điện toán đám mây giúp doanh nghiệp không cần đầu tư hạ tầng vật lý",
    collection, model
)
print(f"Label: {result3_fixed['label']}, Similarity: {result3_fixed['similarity_score']}")

Label: Very Good, Similarity: 0.7518

In [288]:
essay_test_examples = [
    {"student_answer": "Trí tuệ nhân tạo AI hướng đến xây dựng hệ thống có khả năng làm việc như con người, chẳng hạn nhận dạng hình ảnh, hiểu ngôn ngữ, dự đoán. Machine Learning là nhánh của AI giúp hệ thống học từ dữ liệu để đưa ra dự đoán.", "expected": "Very Good", "note": "Câu trả lời đầy đủ, chi tiết"},
    {"student_answer": "Máy tính là thiết bị dùng để chơi game và xem phim giải trí", "expected": "Not Related", "note": "Sai/lạc đề nhưng similarity bị đẩy cao do trùng từ vựng chung"},
    {"student_answer": "Điện toán đám mây giúp doanh nghiệp không cần đầu tư hạ tầng vật lý", "expected": "Very Good", "note": "Paraphrase đúng, ban đầu bị lớp phủ định chấm sai — đã sửa bằng cách tắt kiểm tra xung đột cho luồng essay"},
    {"student_answer": "Cách nấu phở bò truyền thống cần những nguyên liệu gì", "expected": "Not Related", "note": "Hoàn toàn ngoài phạm vi tài liệu"},
]

import json
with open("essay_test_examples.json", "w", encoding="utf-8") as f:
    json.dump(essay_test_examples, f, ensure_ascii=False, indent=2)

print("Đã lưu ví dụ test cho Ngày 13")

Đã lưu ví dụ test cho Ngày 13

In [289]:
from app.text_processing import clean_text, is_empty_answer

print(clean_text("  Nước SÔI ở 100 Độ C,   đúng không???   "))
print(is_empty_answer(""))

nước sôi ở 100 độ c đúng không
True

In [290]:
from app.scoring import classify_answer

result = classify_answer(
    "Nước sôi ở 100 độ C tại áp suất khí quyển tiêu chuẩn",
    "Nước sôi ở 100 độ C khi áp suất bình thường"
)
print(result)

Đang load Sentence Transformer model...
Model đã sẵn sàng.
{'label': 'Very Good', 'similarity_score': 0.9737, 'conflict_detected': False, 'reason': None}

In [291]:
from app.pdf_processing import process_pdf_to_chunks
from app.vector_store import add_document_to_db, retrieve_relevant_chunks, collection
from app.essay_evaluation import evaluate_essay_answer

print(collection.count())

result = evaluate_essay_answer("Trí tuệ nhân tạo là công nghệ giúp máy tính học từ dữ liệu")
print(result['label'], result['similarity_score'])

16
Partially Relevant 0.6872