In [5]:
import pandas as pd

df = pd.read_csv("test_data.csv")

In [6]:
df.head()

,reference_text,student_answer,expected_level
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,Partially Relevant
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,NaN,Not Related
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good

In [7]:
df.shape

(30, 3)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reference_text  30 non-null     str
 1   student_answer  26 non-null     str
 2   expected_level  30 non-null     str
dtypes: str(3)
memory usage: 852.0 bytes

In [9]:
df.columns

Index(['reference_text', 'student_answer', 'expected_level'], dtype='str')

In [10]:
df.isnull()

    reference_text  student_answer  expected_level
0            False           False           False
1            False           False           False
2            False           False           False
3            False            True           False
4            False           False           False
5            False           False           False
6            False           False           False
7            False           False           False
8            False           False           False
9            False           False           False
10           False           False           False
11           False            True           False
12           False           False           False
13           False           False           False
14           False           False           False
15           False           False           False
16           False           False           False
17           False           False           False
18           False           False           False
19           False            True           False
20           False           False           False
21           False           False           False
22           False           False           False
23           False           False           False
24           False           False           False
25           False           False           False
26           False           False           False
27           False            True           False
28           False           False           False
29           False           False           False

In [11]:
df.isnull().sum()

reference_text    0
student_answer    4
expected_level    0
dtype: int64

In [12]:
df[df['student_answer'].isnull()]

,reference_text,student_answer,expected_level
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,NaN,Not Related
11,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,NaN,Not Related
19,DNA mang thông tin di truyền của sinh vật,NaN,Not Related
27,Kim loại dẫn điện tốt vì có electron tự do,NaN,Not Related

In [13]:
df_dropped = df.dropna(subset=['student_answer'])
df_dropped.shape

(26, 3)

In [14]:
df_filled = df.fillna({'student_answer': ''})
df_filled.isnull().sum()

reference_text    0
student_answer    0
expected_level    0
dtype: int64

In [15]:
print("Số dòng gốc:", df.shape[0])
print("Số dòng sau khi dropna:", df_dropped.shape[0])
print("Số dòng sau khi fillna:", df_filled.shape[0])

Số dòng gốc: 30
Số dòng sau khi dropna: 26
Số dòng sau khi fillna: 30

In [16]:
very_good_only = df[df['expected_level'] == 'Very Good']
very_good_only

,reference_text,student_answer,expected_level
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất di chuyển vòng quanh Mặt Trời,Very Good
12,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Vật có khối lượng thì hút nhau,Very Good
16,DNA mang thông tin di truyền của sinh vật,DNA chứa mã di truyền quy định đặc điểm sinh vật,Very Good
20,Áp suất khí quyển giảm dần khi lên cao,Càng lên cao áp suất không khí càng thấp,Very Good
24,Kim loại dẫn điện tốt vì có electron tự do,Electron tự do trong kim loại giúp dẫn điện,Very Good
28,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim bơm máu đi nuôi cơ thể,Very Good

In [17]:
# Very Good VÀ có student_answer không rỗng
result = df[(df['expected_level'] == 'Very Good') & (df['student_answer'].notnull())]
result

,reference_text,student_answer,expected_level
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất di chuyển vòng quanh Mặt Trời,Very Good
12,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Vật có khối lượng thì hút nhau,Very Good
16,DNA mang thông tin di truyền của sinh vật,DNA chứa mã di truyền quy định đặc điểm sinh vật,Very Good
20,Áp suất khí quyển giảm dần khi lên cao,Càng lên cao áp suất không khí càng thấp,Very Good
24,Kim loại dẫn điện tốt vì có electron tự do,Electron tự do trong kim loại giúp dẫn điện,Very Good
28,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim bơm máu đi nuôi cơ thể,Very Good

In [18]:
df['expected_level'].value_counts()

expected_level
Not Related           15
Very Good              8
Partially Relevant     7
Name: count, dtype: int64

In [19]:
df[['reference_text', 'student_answer']]

,reference_text,student_answer
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,NaN
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...
5,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây cần nước để sống và phát triển
6,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Con mèo là động vật có vú
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây không quang hợp vào ban đêm
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất di chuyển vòng quanh Mặt Trời
9,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Mặt Trời quay quanh Trái Đất
10,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,Trái Đất có hình tròn
11,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,NaN
12,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Vật có khối lượng thì hút nhau
13,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Trái Đất hút mọi vật xuống dưới
14,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Nam châm hút sắt
15,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Không có lực nào giữa hai vật có khối lượng
16,DNA mang thông tin di truyền của sinh vật,DNA chứa mã di truyền quy định đặc điểm sinh vật
17,DNA mang thông tin di truyền của sinh vật,DNA là một phần của tế bào
18,DNA mang thông tin di truyền của sinh vật,Protein cấu tạo nên cơ thể
19,DNA mang thông tin di truyền của sinh vật,NaN
20,Áp suất khí quyển giảm dần khi lên cao,Càng lên cao áp suất không khí càng thấp
21,Áp suất khí quyển giảm dần khi lên cao,Trên núi cao không khí loãng hơn
22,Áp suất khí quyển giảm dần khi lên cao,Áp suất khí quyển tăng khi lên cao
23,Áp suất khí quyển giảm dần khi lên cao,Nhiệt độ giảm khi lên cao
24,Kim loại dẫn điện tốt vì có electron tự do,Electron tự do trong kim loại giúp dẫn điện
25,Kim loại dẫn điện tốt vì có electron tự do,Kim loại có thể dẫn điện
26,Kim loại dẫn điện tốt vì có electron tự do,Gỗ không dẫn điện
27,Kim loại dẫn điện tốt vì có electron tự do,NaN
28,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim bơm máu đi nuôi cơ thể
29,Hệ tuần hoàn vận chuyển máu đi khắp cơ thể nhờ...,Tim không tham gia vào việc vận chuyển máu

In [20]:
df[df['expected_level'] == 'Partially Relevant'][['reference_text', 'student_answer']]

,reference_text,student_answer
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu
5,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây cần nước để sống và phát triển
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây không quang hợp vào ban đêm
13,Lực hấp dẫn là lực hút giữa hai vật có khối lượng,Trái Đất hút mọi vật xuống dưới
17,DNA mang thông tin di truyền của sinh vật,DNA là một phần của tế bào
21,Áp suất khí quyển giảm dần khi lên cao,Trên núi cao không khí loãng hơn
25,Kim loại dẫn điện tốt vì có electron tự do,Kim loại có thể dẫn điện

In [21]:
for index, row in df.iterrows():
    print(index, "-", row['reference_text'][:30], "->", row['student_answer'])

0 - Nước sôi ở 100 độ C tại áp suấ -> Nước sôi ở 100 độ C khi áp suất bình thường
1 - Nước sôi ở 100 độ C tại áp suấ -> Nước sôi khi đun nóng đủ lâu
2 - Nước sôi ở 100 độ C tại áp suấ -> Nước không sôi ở 100 độ C
3 - Nước sôi ở 100 độ C tại áp suấ -> nan
4 - Quang hợp là quá trình cây xan -> Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và nước
5 - Quang hợp là quá trình cây xan -> Cây cần nước để sống và phát triển
6 - Quang hợp là quá trình cây xan -> Con mèo là động vật có vú
7 - Quang hợp là quá trình cây xan -> Cây không quang hợp vào ban đêm
8 - Trái Đất quay quanh Mặt Trời t -> Trái Đất di chuyển vòng quanh Mặt Trời
9 - Trái Đất quay quanh Mặt Trời t -> Mặt Trời quay quanh Trái Đất
10 - Trái Đất quay quanh Mặt Trời t -> Trái Đất có hình tròn
11 - Trái Đất quay quanh Mặt Trời t -> nan
12 - Lực hấp dẫn là lực hút giữa ha -> Vật có khối lượng thì hút nhau
13 - Lực hấp dẫn là lực hút giữa ha -> Trái Đất hút mọi vật xuống dưới
14 - Lực hấp dẫn là lực hút giữa ha -> Nam châm hút sắt
15 - Lực hấp dẫn là lực hút giữa ha -> Không có lực nào giữa hai vật có khối lượng
16 - DNA mang thông tin di truyền c -> DNA chứa mã di truyền quy định đặc điểm sinh vật
17 - DNA mang thông tin di truyền c -> DNA là một phần của tế bào
18 - DNA mang thông tin di truyền c -> Protein cấu tạo nên cơ thể
19 - DNA mang thông tin di truyền c -> nan
20 - Áp suất khí quyển giảm dần khi -> Càng lên cao áp suất không khí càng thấp
21 - Áp suất khí quyển giảm dần khi -> Trên núi cao không khí loãng hơn
22 - Áp suất khí quyển giảm dần khi -> Áp suất khí quyển tăng khi lên cao
23 - Áp suất khí quyển giảm dần khi -> Nhiệt độ giảm khi lên cao
24 - Kim loại dẫn điện tốt vì có el -> Electron tự do trong kim loại giúp dẫn điện
25 - Kim loại dẫn điện tốt vì có el -> Kim loại có thể dẫn điện
26 - Kim loại dẫn điện tốt vì có el -> Gỗ không dẫn điện
27 - Kim loại dẫn điện tốt vì có el -> nan
28 - Hệ tuần hoàn vận chuyển máu đi -> Tim bơm máu đi nuôi cơ thể
29 - Hệ tuần hoàn vận chuyển máu đi -> Tim không tham gia vào việc vận chuyển máu

In [22]:
for index, row in df.iterrows():
    ref = row['reference_text']
    student = row['student_answer']
    expected = row['expected_level']
    
    # Giả lập: nếu student_answer trống -> luôn là Not Related
    if pd.isnull(student) or student.strip() == '':
        predicted = 'Not Related'
    else:
        predicted = 'Chưa tính được (chưa có model)'
    
    # So sánh dự đoán giả với nhãn thật
    match = "✓" if predicted == expected else "✗"
    print(f"[{index}] {match} Expected: {expected} | Predicted: {predicted}")

[0] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[1] ✗ Expected: Partially Relevant | Predicted: Chưa tính được (chưa có model)
[2] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[3] ✓ Expected: Not Related | Predicted: Not Related
[4] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[5] ✗ Expected: Partially Relevant | Predicted: Chưa tính được (chưa có model)
[6] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[7] ✗ Expected: Partially Relevant | Predicted: Chưa tính được (chưa có model)
[8] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[9] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[10] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[11] ✓ Expected: Not Related | Predicted: Not Related
[12] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[13] ✗ Expected: Partially Relevant | Predicted: Chưa tính được (chưa có model)
[14] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[15] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[16] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[17] ✗ Expected: Partially Relevant | Predicted: Chưa tính được (chưa có model)
[18] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[19] ✓ Expected: Not Related | Predicted: Not Related
[20] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[21] ✗ Expected: Partially Relevant | Predicted: Chưa tính được (chưa có model)
[22] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[23] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[24] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[25] ✗ Expected: Partially Relevant | Predicted: Chưa tính được (chưa có model)
[26] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)
[27] ✓ Expected: Not Related | Predicted: Not Related
[28] ✗ Expected: Very Good | Predicted: Chưa tính được (chưa có model)
[29] ✗ Expected: Not Related | Predicted: Chưa tính được (chưa có model)

In [23]:
# Cách này CHẬM hơn với dữ liệu lớn (không cần đổi gì bây giờ, chỉ để biết)
for index, row in df.iterrows():
    pass

# Cách nhanh hơn cho việc áp dụng 1 hàm lên toàn bộ cột (sẽ dùng ở Ngày 9, 13)
# df['result'] = df['student_answer'].apply(some_function)

In [24]:
df_filled = df.fillna({'student_answer': ''})

In [25]:
df_filled.to_csv("test_data_cleaned.csv", index=False)

In [26]:
check = pd.read_csv("test_data_cleaned.csv")
check.info()
check.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reference_text  30 non-null     str
 1   student_answer  26 non-null     str
 2   expected_level  30 non-null     str
dtypes: str(3)
memory usage: 852.0 bytes

reference_text    0
student_answer    4
expected_level    0
dtype: int64

In [27]:
def to_lowercase(text):
    return text.lower()

In [28]:
print(to_lowercase("Nước SÔI ở 100 Độ C"))
print(to_lowercase("KHÔNG có gì cả"))
print(to_lowercase("Trái Đất Quay Quanh Mặt Trời"))

nước sôi ở 100 độ c
không có gì cả
trái đất quay quanh mặt trời

In [29]:
def to_lowercase(text):
    if pd.isnull(text):
        return ""
    return str(text).lower()

In [30]:
def strip_whitespace(text):
    return text.strip()

In [31]:
import re

def normalize_spaces(text):
    return re.sub(r'\s+', ' ', text)

In [32]:
print(normalize_spaces("nước    sôi ở   100 độ"))
# → "nước sôi ở 100 độ"

nước sôi ở 100 độ

In [33]:
def clean_whitespace(text):
    if pd.isnull(text):
        return ""
    text = str(text).strip()          # xóa đầu/cuối trước
    text = re.sub(r'\s+', ' ', text)  # chuẩn hóa khoảng trắng giữa
    return text

In [34]:
print(clean_whitespace("   nước   sôi ở  100 độ C   "))
# → "nước sôi ở 100 độ C"

nước sôi ở 100 độ C

Bước 3.2: Viết hàm xóa dấu câu cơ bản
Giải thích:
string.punctuation — 1 chuỗi có sẵn trong thư viện string, liệt kê hết các ký tự dấu câu tiếng Anh chuẩn (bao gồm cả %, - — nên nếu dùng nguyên bản này sẽ xóa luôn cả 2 ký tự bạn có thể muốn giữ theo bảng ở Bước 3.1).
str.maketrans('', '', string.punctuation) — tạo ra 1 "bảng chuyển đổi" (translation table): 2 tham số đầu rỗng nghĩa là không thay ký tự nào bằng ký tự khác, tham số thứ 3 là danh sách ký tự cần xóa hẳn.
.translate(translator) — áp bảng chuyển đổi đó lên chuỗi.

In [35]:
import string

def remove_punctuation(text):
    # string.punctuation chứa: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

In [36]:
import string

def remove_punctuation(text):
    if pd.isnull(text):
        return ""
    # Loại bỏ dấu câu nhưng GIỮ LẠI ký tự %
    punctuation_to_remove = string.punctuation.replace('%', '')
    translator = str.maketrans('', '', punctuation_to_remove)
    return str(text).translate(translator)

In [37]:
test_cases = [
    "Nước sôi ở 100 độ C, đúng không?",
    "Tỷ lệ tăng 20% - rất đáng kể!",
    "Câu hỏi: Trái Đất có hình gì???",
]

for t in test_cases:
    print(f"Gốc:  {t}")
    print(f"Sạch: {remove_punctuation(t)}")
    print()

Gốc:  Nước sôi ở 100 độ C, đúng không?
Sạch: Nước sôi ở 100 độ C đúng không

Gốc:  Tỷ lệ tăng 20% - rất đáng kể!
Sạch: Tỷ lệ tăng 20%  rất đáng kể

Gốc:  Câu hỏi: Trái Đất có hình gì???
Sạch: Câu hỏi Trái Đất có hình gì

In [38]:
def clean_text(text):
    if pd.isnull(text):
        return ""
    
    text = str(text)
    text = to_lowercase(text)
    text = remove_punctuation(text)
    text = clean_whitespace(text)
    
    return text

In [39]:
test_cases = [
    "   Nước SÔI ở 100 Độ C,   đúng không???   ",
    "TỶ  Lệ   tăng 20%!!! - Rất Đáng   Kể",
    "",
    None,
]

for t in test_cases:
    print(f"Gốc:  {repr(t)}")
    print(f"Sạch: {repr(clean_text(t))}")
    print()

Gốc:  '   Nước SÔI ở 100 Độ C,   đúng không???   '
Sạch: 'nước sôi ở 100 độ c đúng không'

Gốc:  'TỶ  Lệ   tăng 20%!!! - Rất Đáng   Kể'
Sạch: 'tỷ lệ tăng 20% rất đáng kể'

Gốc:  ''
Sạch: ''

Gốc:  None
Sạch: ''

In [40]:
df = pd.read_csv("test_data.csv")
df.shape

(30, 3)

In [41]:
df['reference_text_clean'] = df['reference_text'].apply(clean_text)
df['student_answer_clean'] = df['student_answer'].apply(clean_text)

In [42]:
df.shape       # phải là (30, 5) — có thêm 2 cột mới
df.columns     # xác nhận tên 2 cột mới đã đúng

Index(['reference_text', 'student_answer', 'expected_level',
       'reference_text_clean', 'student_answer_clean'],
      dtype='str')

In [43]:
df[['reference_text', 'reference_text_clean']].head(10)

,reference_text,reference_text_clean
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...
5,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...
6,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,trái đất quay quanh mặt trời theo quỹ đạo hình...
9,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,trái đất quay quanh mặt trời theo quỹ đạo hình...

In [44]:
df[['student_answer', 'student_answer_clean']].head(10)

,student_answer,student_answer_clean
0,Nước sôi ở 100 độ C khi áp suất bình thường,nước sôi ở 100 độ c khi áp suất bình thường
1,Nước sôi khi đun nóng đủ lâu,nước sôi khi đun nóng đủ lâu
2,Nước không sôi ở 100 độ C,nước không sôi ở 100 độ c
3,NaN,
4,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,cây dùng ánh sáng để tạo ra thức ăn từ co2 và ...
5,Cây cần nước để sống và phát triển,cây cần nước để sống và phát triển
6,Con mèo là động vật có vú,con mèo là động vật có vú
7,Cây không quang hợp vào ban đêm,cây không quang hợp vào ban đêm
8,Trái Đất di chuyển vòng quanh Mặt Trời,trái đất di chuyển vòng quanh mặt trời
9,Mặt Trời quay quanh Trái Đất,mặt trời quay quanh trái đất

In [45]:
df[df['student_answer'].isnull()][['student_answer', 'student_answer_clean']]

   student_answer student_answer_clean
3             NaN
11            NaN
19            NaN
27            NaN

In [46]:
df['len_before'] = df['reference_text'].fillna('').apply(len)
df['len_after'] = df['reference_text_clean'].apply(len)
df[['reference_text', 'reference_text_clean', 'len_before', 'len_after']].head(10)

,reference_text,reference_text_clean,len_before,len_after
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,52,52
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,52,52
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,52,52
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,52,52
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...,81,81
5,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...,81,81
6,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...,81,81
7,Quang hợp là quá trình cây xanh chuyển hóa CO2...,quang hợp là quá trình cây xanh chuyển hóa co2...,81,81
8,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,trái đất quay quanh mặt trời theo quỹ đạo hình...,51,51
9,Trái Đất quay quanh Mặt Trời theo quỹ đạo hình...,trái đất quay quanh mặt trời theo quỹ đạo hình...,51,51

In [48]:
df_to_save = df.drop(columns=['len_before', 'len_after'])

In [49]:
df_to_save.to_csv("test_data_step3.csv", index=False)

In [50]:
check = pd.read_csv("test_data_step3.csv")
check.info()
check.head()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        26 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  26 non-null     str
dtypes: str(5)
memory usage: 1.3 KB

,reference_text,student_answer,expected_level,reference_text_clean,student_answer_clean
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c khi áp suất bình thường
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,Partially Relevant,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước sôi khi đun nóng đủ lâu
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước không sôi ở 100 độ c
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,NaN,Not Related,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,NaN
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good,quang hợp là quá trình cây xanh chuyển hóa co2...,cây dùng ánh sáng để tạo ra thức ăn từ co2 và ...

In [51]:
import inspect
print(inspect.getsource(clean_text))

def clean_text(text):
    if pd.isnull(text):
        return ""

    text = str(text)
    text = to_lowercase(text)
    text = remove_punctuation(text)
    text = clean_whitespace(text)

    return text

In [52]:
df['reference_text_clean'] = df['reference_text'].apply(clean_text)
df['student_answer_clean'] = df['student_answer'].apply(clean_text)

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        26 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  30 non-null     str
 5   len_before            30 non-null     int64
 6   len_after             30 non-null     int64
dtypes: int64(2), str(5)
memory usage: 1.8 KB

In [54]:
df.loc[3, ['student_answer', 'student_answer_clean']]

student_answer          NaN
student_answer_clean
Name: 3, dtype: str

In [55]:
print(repr(df.loc[3, 'student_answer_clean']))

''

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        26 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  30 non-null     str
 5   len_before            30 non-null     int64
 6   len_after             30 non-null     int64
dtypes: int64(2), str(5)
memory usage: 1.8 KB

In [57]:
df.to_csv("test_data_step3.csv", index=False)

In [58]:
check = pd.read_csv("test_data_step3.csv")
check.info()
check.head()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        26 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  26 non-null     str
 5   len_before            30 non-null     int64
 6   len_after             30 non-null     int64
dtypes: int64(2), str(5)
memory usage: 1.8 KB

,reference_text,student_answer,expected_level,reference_text_clean,student_answer_clean,len_before,len_after
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c khi áp suất bình thường,52,52
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,Partially Relevant,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước sôi khi đun nóng đủ lâu,52,52
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước không sôi ở 100 độ c,52,52
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,NaN,Not Related,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,NaN,52,52
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good,quang hợp là quá trình cây xanh chuyển hóa co2...,cây dùng ánh sáng để tạo ra thức ăn từ co2 và ...,81,81

In [64]:
df_to_save = df.drop(columns=['len_before', 'len_after'])
df_to_save.to_csv("test_data_step3.csv", index=False)

In [65]:
check = pd.read_csv("test_data_step3.csv")
check.info()
check.head()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        26 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  26 non-null     str
dtypes: str(5)
memory usage: 1.3 KB

,reference_text,student_answer,expected_level,reference_text_clean,student_answer_clean
0,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi ở 100 độ C khi áp suất bình thường,Very Good,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước sôi ở 100 độ c khi áp suất bình thường
1,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước sôi khi đun nóng đủ lâu,Partially Relevant,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước sôi khi đun nóng đủ lâu
2,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,Nước không sôi ở 100 độ C,Not Related,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,nước không sôi ở 100 độ c
3,Nước sôi ở 100 độ C tại áp suất khí quyển tiêu...,NaN,Not Related,nước sôi ở 100 độ c tại áp suất khí quyển tiêu...,NaN
4,Quang hợp là quá trình cây xanh chuyển hóa CO2...,Cây dùng ánh sáng để tạo ra thức ăn từ CO2 và ...,Very Good,quang hợp là quá trình cây xanh chuyển hóa co2...,cây dùng ánh sáng để tạo ra thức ăn từ co2 và ...

In [66]:
check = pd.read_csv("test_data_step3.csv", keep_default_na=False, na_values=[])
check.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        30 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  30 non-null     str
dtypes: str(5)
memory usage: 1.3 KB

In [67]:
check.info()
print(repr(check.loc[3, 'student_answer_clean']))

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reference_text        30 non-null     str
 1   student_answer        30 non-null     str
 2   expected_level        30 non-null     str
 3   reference_text_clean  30 non-null     str
 4   student_answer_clean  30 non-null     str
dtypes: str(5)
memory usage: 1.3 KB
''